// js/wordbank.js
// Anda dapat menempelkan ribuan baris kosakata di antara tanda backtick (`) di bawah ini.
// Format: Bahasa Inggris = Arti Bahasa Indonesia (1 pasang per baris)

window.DEFAULT_WORDBANK_RAW = `
abandon = meninggalkan / membuang
ability = kemampuan / keahlian
able = mampu / bisa
about = tentang / sekitar
above = di atas / melebihi
abroad = luar negeri
absence = ketidakhadiran / absen
absolute = mutlak / pasti
absorb = menyerap
abuse = menyalahgunakan / pelecehan
academic = akademik
accept = menerima / menyetujui
access = akses / jalan masuk
accident = kecelakaan / kebetulan
accompany = menemani / menyertai
accomplish = menyelesaikan / mencapai
according = menurut / sesuai
account = akun / rekening
accurate = akurat / tepat
accuse = menuduh / mendakwa
achieve = mencapai / meraih
achievement = pencapaian / prestasi
acid = asam
acknowledge = mengakui
acquire = memperoleh / mendapatkan
across = di seberang / melintasi
act = bertindak / babak
action = tindakan / aksi
active = aktif / giat
activity = aktivitas / kegiatan
actor = aktor / pemeran
actual = sebenarnya / nyata
actually = sebenarnya / sesungguhnya
adapt = beradaptasi / menyesuaikan
add = menambah / menjumlahkan
addition = tambahan / penjumlahan
additional = tambahan
address = alamat / menyapa
adequate = memadai / cukup
adjust = menyesuaikan / mengatur
administration = administrasi / pemerintahan
admire = mengagumi
admission = pengakuan / izin masuk
admit = mengakui / mengizinkan masuk
adopt = mengadopsi / mengambil
adult = dewasa
advance = kemajuan / maju
advanced = lanjutan / canggih
advantage = keuntungan / kelebihan
adventure = petualangan
advertising = periklanan
advice = nasihat / saran
advise = menasihati / menyarankan
affair = urusan / peristiwa
affect = memengaruhi
afford = mampu membeli / sanggup
afraid = takut / khawatir
after = setelah / sesudah
afternoon = sore / siang
again = lagi / kembali
against = melawan / terhadap
age = umur / zaman
agency = agen / badan
agenda = agenda / jadwal acara
agent = agen / perwakilan
aggressive = agresif / menyerang
ago = yang lalu
agree = setuju / sepakat
agreement = persetujuan / kesepakatan
agriculture = pertanian
ahead = di depan / lebih dulu
aid = bantuan / menolong
aim = tujuan / membidik
air = udara
aircraft = pesawat terbang
airline = maskapai penerbangan
airport = bandara
alarm = alarm / tanda bahaya
album = album
alcohol = alkohol
alive = hidup / masih hidup
all = semua / seluruh
allow = mengizinkan / membiarkan
almost = hampir / nyaris
alone = sendirian / tunggal
along = sepanjang / bersama
already = sudah / telah
also = juga / selain itu
alter = mengubah / mengganti
alternative = alternatif / pilihan lain
although = meskipun / walaupun
always = selalu / senantiasa
amaze = menakjubkan / membuat kagum
ambition = ambisi / cita-cita
among = di antara
amount = jumlah / nilai
analysis = analisis / kajian
analyze = menganalisis / mengkaji
ancient = kuno / purba
and = dan
anger = kemarahan / amarah
angle = sudut / sudut pandang
angry = marah / murka
animal = hewan / binatang
anniversary = hari jadi / ulang tahun
announce = mengumumkan
annual = tahunan
another = yang lain / satu lagi
answer = jawaban / menjawab
anticipate = mengantisipasi / mengharapkan
anxiety = kecemasan / kegelisahan
anxious = cemas / gelisah
any = apa saja / berapa pun
anybody = siapa saja / siapa pun
anymore = lagi / tidak lagi
anyone = siapa saja / siapa pun
anything = apa saja / apa pun
anyway = bagaimanapun / ngomong-ngomong
anywhere = di mana saja / ke mana pun
apart = terpisah / selain
apartment = apartemen
apologize = meminta maaf
apparent = jelas / tampak
apparently = rupanya / tampaknya
appeal = daya tarik / memohon
appear = muncul / tampak
appearance = penampilan / kemunculan
apple = apel
application = aplikasi / lamaran
apply = melamar / menerapkan
appoint = menunjuk / menetapkan
appointment = janji temu / penunjukan
appreciate = menghargai / mengapresiasi
approach = pendekatan / mendekati
appropriate = tepat / sesuai
approval = persetujuan / restu
approve = menyetujui / mengesahkan
approximately = kira-kira / sekitar
architect = arsitek
architecture = arsitektur
area = area / wilayah
argue = berdebat / membantah
argument = argumen / perdebatan
arise = muncul / timbul
arm = lengan / senjata
armed = bersenjata
army = tentara / angkatan darat
around = di sekitar / mengelilingi
arrange = mengatur / menyusun
arrangement = pengaturan / susunan
arrest = menangkap / penangkapan
arrival = kedatangan
arrive = tiba / sampai
art = seni
article = artikel / barang
artist = seniman / artis
artistic = artistik / berseni
as = sebagai / karena / seperti
ashamed = malu
aside = di samping / ke samping
ask = bertanya / meminta
asleep = tertidur / tidur
aspect = aspek / segi
assault = penyerangan / menyerang
assert = menegaskan / menyatakan
assess = menilai / menaksir
assessment = penilaian / taksiran
asset = aset / harta
assign = menugaskan / menetapkan
assignment = tugas / penugasan
assist = membantu / menolong
assistance = bantuan / pertolongan
assistant = asisten / pembantu
associate = menghubungkan / rekan
association = asosiasi / perkumpulan
assume = berasumsi / menganggap
assumption = asumsi / anggapan
assure = meyakinkan / menjamin
at = di / pada
athlete = atlet / olahragawan
atmosphere = atmosfer / suasana
attach = melampirkan / menempelkan
attack = menyerang / serangan
attempt = mencoba / usaha
attend = menghadiri / memperhatikan
attention = perhatian
attitude = sikap / perilaku
attorney = pengacara / jaksa
attract = menarik / memikat
attractive = menarik / menawan
attribute = atribut / sifat
audience = penonton / hadirin
author = penulis / pengarang
authority = otoritas / wewenang
auto = otomatis / mobil
available = tersedia / ada
average = rata-rata / biasa
avoid = menghindari / menjauhi
award = penghargaan / hadiah
aware = sadar / tahu
awareness = kesadaran
away = jauh / pergi
awful = mengerikan / sangat buruk
baby = bayi
back = belakang / kembali / punggung
background = latar belakang
bad = buruk / jahat
badly = dengan buruk / sangat
bag = tas / kantong
bake = memanggang / membakar
balance = keseimbangan / saldo
ball = bola
ban = melarang / larangan
band = pita / grup musik
bank = bank / tepi sungai
bar = batang / bar / menghalangi
barely = hampir tidak / baru saja
barrel = tong / barel
barrier = penghalang / rintangan
base = dasar / markas
basic = dasar / pokok
basically = pada dasarnya
basis = dasar / landasan
basket = keranjang
basketball = bola basket
bath = mandi / bak mandi
bathroom = kamar mandi
battery = baterai / aki
battle = pertempuran / berjuang
be = menjadi / ada
beach = pantai
bean = kacang / biji
bear = beruang / menanggung
V = mengalahkan / memukul / detak
beautiful = indah / cantik
beauty = keindahan / kecantikan
because = karena / sebab
become = menjadi
bed = tempat tidur / kasur
bedroom = kamar tidur
beer = bir
before = sebelum / di depan
begin = mulai / memulai
beginning = awal / permulaan
behavior = perilaku / tingkah laku
behind = di belakang / tertinggal
being = makhluk / keberadaan
belief = kepercayaan / keyakinan
believe = percaya / yakin
bell = bel / lonceng
belong = milik / termasuk
below = di bawah
belt = sabuk / ikat pinggang
bench = bangku
bend = membungkuk / menekuk
beneath = di bawah
benefit = manfaat / keuntungan
beside = di samping / di sebelah
besides = selain itu / di samping itu
best = terbaik / paling baik
bet = bertaruh / taruhan
better = lebih baik
between = di antara
beyond = di luar / melewati
bible = alkitab
big = besar / dewasa
bike = sepeda / motor
bill = tagihan / rancangan undang-undang
billion = miliar
bind = mengikat / menjilid
biological = biologis
bird = burung
birth = kelahiran
birthday = ulang tahun
bit = sedikit / potongan kecil
bite = menggigit / gigitan
black = hitam / gelap
blade = bilah / mata pisau
blame = menyalahkan / kesalahan
blanket = selimut
blind = buta / tirai
block = blok / menghalangi
blood = darah
blow = meniup / pukulan
blue = biru / sedih
board = papan / dewan / naik
boat = perahu / kapal
body = tubuh / badan
boil = mendidih / merebus
bomb = bom / mengebom
bond = ikatan / obligasi
bone = tulang / duri
book = buku / memesan
boom = ledakan / berkembang pesat
boot = sepatu bot / bagasi mobil
border = perbatasan / tepi
born = lahir
borrow = meminjam
boss = bos / atasan
both = keduanya / baik... maupun
bother = mengganggu / repot
bottle = botol
bottom = bawah / dasar
boundary = batas / perbatasan
bowl = mangkuk
box = kotak / tinju
boy = anak laki-laki
boyfriend = pacar laki-laki
brain = otak
branch = cabang / ranting
brand = merek / cap
brave = berani
bread = roti
break = istirahat / merusak / memecahkan
breakfast = sarapan
breast = dada / payudara
breath = napas
breathe = bernapas
brick = batu bata
bridge = jembatan
brief = singkat / ringkas
briefly = secara singkat
bright = terang / cerdas
brilliant = cemerlang / brilian
bring = membawa
broad = luas / lebar
broken = rusak / patah
brother = saudara laki-laki
brown = cokelat
brush = sikat / menyikat / kuas
buck = dolar / rusa jantan
budget = anggaran
build = membangun / mendirikan
building = bangunan / gedung
bullet = peluru
bunch = seikat / sekumpulan
burden = beban / membebani
burn = membakar / terbakar
bury = mengubur / memendam
bus = bus
business = bisnis / urusan
busy = sibuk / ramai
but = tetapi / namun / kecuali
butter = mentega
button = tombol / kancing
buy = membeli
buyer = pembeli
by = oleh / dengan / di dekat
cabin = kabin / pondok
cabinet = lemari / kabinet
cable = kabel
cake = kue
calculate = menghitung
call = memanggil / menelepon / panggilan
calm = tenang / menenangkan
camera = kamera
camp = kemah / berkemah
campaign = kampanye
campus = kampus
can = bisa / dapat / kaleng
cancer = kanker
candidate = kandidat / calon
cap = topi / tutup
capability = kemampuan / kapabilitas
capable = mampu / cakap
capacity = kapasitas / daya tampung
capital = ibu kota / modal / huruf besar
captain = kapten
capture = menangkap / merebut
car = mobil
carbon = karbon
card = kartu
care = peduli / perawatan / perhatian
career = karier
careful = hati-hati / teliti
carefully = dengan hati-hati
carrier = pembawa / maskapai
carry = membawa / mengangkat
case = kasus / kotak / wadah
cash = uang tunai
cast = pemeran / melempar / mencetak
cat = kucing
catch = menangkap / mengejar
category = kategori / golongan
cause = penyebab / menyebabkan
ceiling = langit-langit / plafon
celebrate = merayakan
celebration = perayaan
celebrity = selebriti / orang terkenal
cell = sel / bilik
center = pusat / tengah
central = pusat / sentral
century = abad
ceremony = upacara
certain = pasti / tertentu
certainly = tentu saja / pasti
chain = rantai / jaringan
chair = kursi / ketua
chairman = ketua / pimpinan
challenge = tantangan / menantang
chamber = ruang / kamar
champion = juara / pembela
championship = kejuaraan
chance = kesempatan / peluang / kebetulan
change = perubahan / mengubah / kembalian
changing = berubah / pergantian
channel = saluran / kanal
chapter = bab / cabang
character = karakter / sifat / tokoh
characteristic = karakteristik / ciri khas
characterize = mencirikan / menggambarkan
charge = biaya / mengisi daya / menuduh
charity = amal / badan amal
chart = grafik / bagan
chase = mengejar / pengejaran
cheap = murah
check = memeriksa / cek
cheek = pipi
cheese = keju
chef = koki / juru masak
chemical = bahan kimia / kimiawi
chest = dada / peti
chicken = ayam
chief = kepala / pemimpin / utama
child = anak
childhood = masa kecil / masa kanak-kanak
chill = dingin / bersantai
chin = dagu
chip = keripik / kepingan
chocolate = cokelat
choice = pilihan / alternatif
cholesterol = kolesterol
choose = memilih
chop = memotong / mencincang
church = gereja
cigarette = rokok
circle = lingkaran / melingkari
circumstance = keadaan / situasi
cite = mengutip / menyebut
citizen = warga negara / penduduk
city = kota
civil = sipil / sopan
civilian = warga sipil
claim = klaim / mengklaim / menuntut
class = kelas / golongan
classic = klasik
classroom = ruang kelas
clean = bersih / membersihkan
clear = jelas / bersih / membersihkan
clearly = dengan jelas
client = klien / pelanggan
climate = iklim / suasana
climb = memanjat / mendaki
clinic = klinik
clinical = klinis
clock = jam dinding
close = tutup / menutup / dekat
closely = dengan erat / dengan cermat
closer = lebih dekat
clothes = pakaian / baju
clothing = pakaian / sandang
cloud = awan
club = klub / tongkat
clue = petunjuk
cluster = kelompok / gugus
coach = pelatih / melatih
coal = batu bara
coalition = koalisi / gabungan
coast = pantai / pesisir
coat = mantel / jas / lapisan
code = kode / sandi
coffee = kopi
cognitive = kognitif
cold = dingin / flu
collapse = runtuh / roboh / pingsan
colleague = rekan kerja / kolega
collect = mengumpulkan / mengoleksi
collection = koleksi / kumpulan
collective = kolektif / bersama
college = perguruan tinggi / kampus
colonial = kolonial / penjajahan
color = warna / mewarnai
column = kolom / pilar
combination = kombinasi / gabungan
combine = menggabungkan / memadukan
come = datang / tiba
comedy = komedi
comfort = kenyamanan / menghibur
comfortable = nyaman
command = perintah / memerintah
commander = komandan
comment = komentar / mengomentari
commercial = komersial / iklan
commission = komisi / menugaskan
commit = melakukan / berkomitmen
commitment = komitmen / janji
committee = komite / panitia
common = umum / biasa
communicate = berkomunikasi / menyampaikan
communication = komunikasi
community = komunitas / masyarakat
company = perusahaan / teman
compare = membandingkan
comparison = perbandingan
compete = bersaing / berlomba
competition = kompetisi / persaingan
competitive = kompetitif / bersaing
competitor = pesaing / lawan
complain = mengeluh / komplain
complaint = keluhan / pengaduan
complete = lengkap / menyelesaikan
completely = sepenuhnya / sama sekali
complex = kompleks / rumit
complicated = rumit / sulit
component = komponen / bagian
compose = menyusun / mengarang
composition = komposisi / susunan
comprehensive = komprehensif / menyeluruh
computer = komputer
concentrate = berkonsentrasi / memusatkan
concentration = konsentrasi / pemusatan
concept = konsep / gagasan
concern = kekhawatiran / peduli / urusan
concerned = khawatir / peduli
concert = konser
conclude = menyimpulkan / mengakhiri
conclusion = kesimpulan / akhir
concrete = beton / nyata / konkret
condition = kondisi / syarat
conduct = melakukan / perilaku
conference = konferensi / rapat
confidence = kepercayaan diri / keyakinan
confident = percaya diri / yakin
confirm = mengonfirmasi / memastikan
conflict = konflik / pertentangan
confront = menghadapi / menentang
confusion = kebingungan / kekacauan
congress = kongres
connect = menghubungkan / menyambung
connection = koneksi / hubungan
consciousness = kesadaran
consensus = konsensus / kesepakatan bersama
consequence = konsekuensi / akibat
conservative = konservatif / kolot
consider = mempertimbangkan / menganggap
considerable = cukup besar / signifikan
consideration = pertimbangan / perhatian
consist = terdiri dari
consistent = konsisten / tetap
constant = konstan / terus-menerus
constantly = secara terus-menerus / selalu
constitute = membentuk / merupakan
constitutional = konstitusional
construct = membangun / menyusun
construction = konstruksi / pembangunan
consultant = konsultan / penasihat
consume = mengonsumsi / menghabiskan
consumer = konsumen / pemakai
consumption = konsumsi / pemakaian
contact = kontak / menghubungi
contain = berisi / mengandung
container = wadah / kontainer
contemporary = kontemporer / masa kini
content = konten / isi / puas
contest = kontes / lomba / menentang
context = konteks / latar belakang
continue = melanjutkan / terus
continued = berlanjut / terus-menerus
contract = kontrak / menyusut
contrast = kontras / perbedaan
contribute = berkontribusi / menyumbang
contribution = kontribusi / sumbangan
control = kontrol / mengendalikan
controversial = kontroversial
controversy = kontroversi / perdebatan
convention = konvensi / pertemuan besar
conventional = konvensional / biasa
conversation = percakapan / obrolan
convert = mengubah / mengonversi
conviction = keyakinan / vonis hukuman
convince = meyakinkan / membujuk
cook = memasak / juru masak
cookie = kue kering
cooking = memasak / masakan
cool = keren / sejuk / mendinginkan
cooperation = kerja sama
cop = polisi
cope = mengatasi / menanggulangi
copy = salinan / menyalin / meniru
core = inti / pusat
corn = jagung
corner = sudut / pojok
corporate = korporat / perusahaan
corporation = korporasi / perusahaan besar
correct = benar / mengoreksi
correspondent = koresponden / wartawan
cost = biaya / harga / berharga
cotton = kapas / katun
couch = sofa / dipan
could = bisa / dapat (bentuk lampau dari can)
council = dewan
counselor = konselor / penasihat
count = menghitung / hitungan
counter = meja kasir / melawan
country = negara / pedesaan
county = wilayah / daerah setingkat kabupaten
couple = pasangan / beberapa
courage = keberanian
course = kursus / arah / hidangan
court = pengadilan / lapangan olahraga
cousin = sepupu
cover = menutup / sampul / meliput
coverage = cakupan / liputan
cow = sapi
crack = retak / memecahkan
craft = kerajinan / keahlian
crash = tabrakan / menabrak / jatuh
crazy = gila / sangat suka
cream = krim
create = membuat / menciptakan
creation = ciptaan / kreasi
creative = kreatif
creature = makhluk
credit = kredit / penghargaan / pujian
crew = kru / awak
crime = kejahatan / tindak pidana
criminal = kriminal / penjahat
crisis = krisis / masa genting
criteria = kriteria / ukuran
critic = kritikus / pengkritik
critical = kritis / sangat penting
criticism = kritik / kecaman
criticize = mengkritik / mengecam
crop = tanaman pangan / hasil panen / memotong
cross = menyebrang / silang / salib
crowd = kerumunan / orang banyak
crucial = krusial / sangat penting
cry = menangis / berteriak
cultural = budaya / kultural
culture = budaya / kebudayaan
cup = cangkir / piala
curious = penasaran / ingin tahu
current = saat ini / arus
currently = saat ini / sekarang
curriculum = kurikulum
custom = adat / kebiasaan / pesanan khusus
customer = pelanggan / pembeli
cut = memotong / luka potong
cycle = siklus / bersepeda
dad = ayah
daily = harian / setiap hari
damage = kerusakan / merusak
dance = menari / tarian
danger = bahaya
dangerous = berbahaya
dare = berani / menantang
dark = gelap / kegelapan
darkness = kegelapan
data = data / informasi
database = pangkalan data / database
date = tanggal / kencan / kurma
daughter = anak perempuan
day = hari / siang
dead = mati / tewas
deal = kesepakatan / berurusan / membagikan
dealer = pedagang / penyalur
dear = sayang / yang terhormat / mahal
death = kematian
debate = debat / berdebat
debt = utang
decade = dekade / dasawarsa
decide = memutuskan
decision = keputusan
deck = dek / geladak / tumpukan kartu
declare = menyatakan / mendeklarasikan
decline = menurun / menolak / kemunduran
decrease = mengurangi / penurunan
deep = dalam / mendalam
deeply = secara mendalam / sangat
deer = rusa
defeat = mengalahkan / kekalahan
defend = membela / mempertahankan
defendant = terdakwa / tergugat
defense = pertahanan / pembelaan
defensive = defensif / bertahan
deficit = defisit / kekurangan
define = mendefinisikan / menetapkan
definitely = pasti / tentu saja
definition = definisi / pengertian
degree = gelar / derajat / tingkat
delay = menunda / penundaan
deliver = mengirim / menyampaikan / melahirkan
delivery = pengiriman / persalinan
demand = permintaan / menuntut
democracy = demokrasi
democratic = demokratis
demonstrate = mendemonstrasikan / menunjukkan
demonstration = demonstrasi / unjuk rasa
deny = menyangkal / menolak
department = departemen / bagian
depend = bergantung / tergantung
dependent = bergantung / tanggungan
depending = tergantung pada
depict = menggambarkan / melukiskan
depression = depresi / kemerosotan ekonomi
depth = kedalaman
deputy = wakil / deputi
derive = memperoleh / berasal dari
describe = menggambarkan / mendeskripsikan
description = deskripsi / gambaran
desert = gurun / meninggalkan
deserve = pantas mendapatkan / layak
design = desain / merancang
designer = desainer / perancang
desire = keinginan / hasrat / menginginkan
desk = meja kerja / meja tulis
desperate = putus asa / nekat
despite = meskipun / walaupun
destroy = menghancurkan / merusak
destruction = kehancuran / pemusnahan
detail = detail / rincian
detailed = rinci / mendetail
detect = mendeteksi / menemukan
determine = menentukan / menetapkan
develop = mengembangkan / berkembang
developing = berkembang
development = perkembangan / pembangunan
device = perangkat / alat
devote = mengabdikan / mencurahkan
dialogue = dialog / percakapan
die = mati / meninggal
diet = diet / pola makan
differ = berbeda / berselisih
difference = perbedaan / selisih
different = berbeda / lain
differently = secara berbeda
difficult = sulit / susah
difficulty = kesulitan / kesukaran
dig = menggali
digital = digital
dimension = dimensi / ukuran
dining = makan / ruang makan
dinner = makan malam
direct = langsung / mengarahkan
direction = arah / petunjuk
directly = secara langsung
director = direktur / sutradara
dirt = kotoran / tanah
dirty = kotor / curang
disability = disabilitas / cacat
disagree = tidak setuju / berbeda pendapat
disappear = menghilang / lenyap
disaster = bencana / musibah
discipline = disiplin / mendisiplinkan
discourse = wacana / perbincangan
discover = menemukan / mengetahui
discovery = penemuan
discrimination = diskriminasi / pembedaan
discuss = mendiskusikan / membahas
discussion = diskusi / pembahasan
disease = penyakit
dish = hidangan / piring
dismiss = memberhentikan / mengabaikan / membubarkan
disorder = gangguan / kekacauan
display = menampilkan / tampilan / pameran
dispute = perselisihan / sengketa
distance = jarak / kejauhan
distant = jauh / renggang
distinct = berbeda / jelas
distinction = perbedaan / keistimewaan
distinguish = membedakan / mengenali
distribute = mendistribusikan / membagikan
distribution = distribusi / penyaluran
district = distrik / wilayah
diverse = beragam / bermacam-macam
diversity = keberagaman / keragaman
divide = membagi / memisahkan
division = divisi / pembagian
divorce = perceraian / bercerai
do = melakukan / mengerjakan
doctor = dokter
document = dokumen / mendokumentasikan
dog = anjing
domestic = domestik / dalam negeri / rumah tangga
dominant = dominan / berkuasa
dominate = mendominasi / menguasai
door = pintu
double = ganda / dua kali lipat
doubt = keraguan / meragukan
down = turun / ke bawah
downtown = pusat kota
dozen = lusin
draft = draf / konsep / wajib militer
drag = menyeret / menarik
drama = drama / sandiwara
dramatic = dramatis / mencolok
dramatically = secara dramatis / drastis
draw = menggambar / menarik / seri
drawing = gambar / lukisan
dream = mimpi / bermimpi
dress = gaun / berpakaian
drink = minum / minuman
drive = mengemudi / dorongan
driver = pengemudi / sopir
drop = menjatuhkan / tetesan / turun
drug = obat / narkoba
dry = kering / mengeringkan
due = jatuh tempo / karena / hak
during = selama / sewaktu
dust = debu / membersihkan debu
duty = tugas / kewajiban / bea cukai
each = masing-masing / setiap
eager = bersemangat / ingin sekali
ear = telinga / bulir jagung
early = awal / pagi-pagi
earn = menghasilkan (uang) / mendapatkan
earth = bumi / tanah
ease = kemudahan / meredakan
easily = dengan mudah
east = timur
eastern = bagian timur
easy = mudah / gampang
eat = makan
economic = ekonomi / ekonomis
economics = ilmu ekonomi
economist = ekonom / ahli ekonomi
economy = ekonomi / penghematan
edge = tepi / pinggir / keunggulan
edition = edisi / terbitan
editor = editor / penyunting
educate = mendidik / mengajar
education = pendidikan
educational = edukatif / bersifat pendidikan
educator = pendidik / pengajar
effect = efek / dampak / pengaruh
effective = efektif / berhasil guna
effectively = secara efektif / pada kenyataannya
efficiency = efisiensi / daya guna
efficient = efisien / hemat
effort = usaha / upaya
egg = telur
eight = delapan
either = salah satu / juga (dalam kalimat negatif)
elderly = lanjut usia / tua
elect = memilih (melalui pemungutan suara)
election = pemilihan umum / pemilu
electric = listrik / elektrik
electricity = listrik / kelistrikan
electronic = elektronik
element = elemen / unsur
elementary = dasar / tingkat dasar
eliminate = mengeliminasi / menghilangkan
elite = elit / golongan atas
else = lain / kalau tidak
elsewhere = di tempat lain
e-mail = surat elektronik / email
embrace = memeluk / merangkul / menerima
emerge = muncul / tampil
emergency = darurat / keadaan darurat
emission = emisi / pancaran
emotion = emosi / perasaan
emotional = emosional / penuh perasaan
emphasis = penekanan / titik berat
emphasize = menekankan / menitikberatkan
employ = mempekerjakan / menggunakan
employee = karyawan / pegawai
employer = pemberi kerja / majikan
employment = pekerjaan / ketenagakerjaan
empty = kosong / mengosongkan
enable = memungkinkan / mengaktifkan
encounter = menghadapi / bertemu / pertemuan
encourage = mendorong / menyemangati
end = akhir / mengakhiri / tujuan
enemy = musuh / lawan
energy = energi / tenaga
enforcement = penegakan (hukum)
engage = terlibat / menarik perhatian / mempekerjakan
engine = mesin / motor
engineer = insinyur / teknisi
engineering = teknik / rekayasa
enhance = meningkatkan / memperkaya
enjoy = menikmati / menyukai
enormous = sangat besar / luar biasa
enough = cukup / memadai
ensure = memastikan / menjamin
enter = masuk / memasukkan
enterprise = perusahaan / usaha
entertainment = hiburan
entire = seluruh / semua
entirely = sepenuhnya / seluruhnya
entrance = pintu masuk / masuk
entry = masuk / entri / peserta
environment = lingkungan
environmental = lingkungan hidup
episode = episode / babak
equal = sama / setara / menyamai
equally = secara merata / sama-sama
equipment = peralatan / perlengkapan
era = era / zaman
error = kesalahan / galat
escape = melarikan diri / kabur / pelarian
especially = terutama / khususnya
essay = esai / karangan
essential = penting / esensial / pokok
essentially = pada dasarnya / intinya
establish = mendirikan / menetapkan
establishment = pendirian / lembaga
estate = perkebunan / harta warisan / properti
estimate = memperkirakan / perkiraan
etc = dan lain-lain (et cetera)
ethics = etika / moral
ethnic = etnis / suku bangsa
evaluate = mengevaluasi / menilai
evaluation = evaluasi / penilaian
even = bahkan / genap / rata
evening = malam / sore
event = acara / peristiwa
eventually = akhirnya / pada akhirnya
ever = pernah / selalu
every = setiap / tiap-tiap
everybody = semua orang / setiap orang
everyday = sehari-hari / biasa
everyone = semua orang / setiap orang
everything = semuanya / segala sesuatu
everywhere = di mana-mana / ke mana-mana
evidence = bukti / petunjuk
evil = jahat / kejahatan
evolution = evolusi / perkembangan
evolve = berevolusi / berkembang
exact = tepat / persis
exactly = tepat sekali / persis
examination = ujian / pemeriksaan
examine = memeriksa / menguji
example = contoh / teladan
exceed = melebihi / melampaui
excellent = sangat baik / unggul
except = kecuali / selain
exception = pengecualian
exchange = pertukaran / menukar
exciting = menarik / mendebarkan
executive = eksekutif / pemimpin perusahaan
exercise = olahraga / latihan / menggunakan
exhibit = memamerkan / pameran / barang bukti
exhibition = pameran / pertunjukan
exist = ada / eksis
existence = keberadaan / eksistensi
existing = yang ada / saat ini
expand = memperluas / mengembangkan
expansion = ekspansi / perluasan
expect = mengharapkan / memperkirakan
expectation = harapan / ekspektasi
expense = biaya / pengeluaran
expensive = mahal
experience = pengalaman / mengalami
experiment = eksperimen / percobaan
expert = ahli / pakar
explain = menjelaskan / menerangkan
explanation = penjelasan / keterangan
explode = meledak / meledakkan
explore = menjelajahi / menggali
explosion = ledakan
export = ekspor / mengekspor
expose = mengungkap / memaparkan
exposure = paparan / eksposur
express = mengekspresikan / mengungkapkan / cepat
expression = ekspresi / ungkapan
extend = memperpanjang / memperluas
extension = perpanjangan / perluasan / sambungan
extensive = luas / ekstensif
extent = tingkat / luas / batas
external = eksternal / luar
extra = ekstra / tambahan
extraordinary = luar biasa / istimewa
extreme = ekstrem / sangat
extremely = sangat / luar biasa
eye = mata / pandangan
fabric = kain / tekstil / struktur
face = wajah / menghadapi
facility = fasilitas / sarana
fact = fakta / kenyataan
factor = faktor / unsur
factory = pabrik
faculty = fakultas / staf pengajar / bakat
fade = memudar / meredup
fail = gagal / tidak lulus
failure = kegagalan
fair = adil / wajar / pameran / cerah
fairly = secara adil / cukup
faith = iman / kepercayaan
fall = jatuh / musim gugur / turun
false = salah / palsu
familiar = akrab / tidak asing
family = keluarga / famili
famous = terkenal / ternama
fan = penggemar / kipas angin
fantasy = fantasi / khayalan
far = jauh
farm = pertanian / peternakan
farmer = petani / peternak
fashion = mode / cara
fast = cepat / puasa
fat = gemuk / lemak
fate = takdir / nasib
father = ayah / bapak
fault = kesalahan / cacat
favor = bantuan / kebaikan / memihak
favorite = favorit / kesukaan
fear = ketakutan / takut
feature = fitur / ciri khas / menampilkan
federal = federal / serikat
fee = biaya / ongkos / iuran
feed = memberi makan / pakan
feel = merasa / merasakan
feeling = perasaan
fellow = rekan / teman / sesama
female = perempuan / betina
fence = pagar
few = sedikit / beberapa
fewer = lebih sedikit
fiber = serat
fiction = fiksi / cerita rekaan
field = lapangan / bidang / ladang
fifteen = lima belas
fifth = kelima
fifty = lima puluh
fight = berkelahi / berjuang / pertarungan
fighter = petarung / pejuang
fighting = perkelahian / pertempuran
figure = angka / sosok / tokoh / mengira
file = berkas / mengajukan / mengarsipkan
fill = mengisi / memenuhi
film = film / merekam
final = final / terakhir / ujian akhir
finally = akhirnya
finance = keuangan / membiayai
financial = finansial / keuangan
find = menemukan / mencari tahu
finding = temuan / hasil penelitian
fine = baik / denda / halus
finger = jari tangan
finish = selesai / menyelesaikan / akhir
fire = api / kebakaran / memecat / menembak
firm = perusahaan / tegas / kokoh
first = pertama / mula-mula
fish = ikan / memancing
fishing = memancing / perikanan
fit = cocok / bugar / muat
fitness = kebugaran / kesehatan
five = lima
fix = memperbaiki / menetapkan
flag = bendera / menandai
flame = nyala api / kobaran api
flat = datar / rata / apartemen / kempes
flavor = rasa / aroma
flee = melarikan diri / mengungsi
flesh = daging (manusia/hewan)
flight = penerbangan / pelarian
float = mengapung / melayang
floor = lantai / dasar
flow = mengalir / aliran
flower = bunga
fly = terbang / menerbangkan / lalat
focus = fokus / memusatkan
folk = rakyat / orang-orang / musik tradisional
follow = mengikuti / mematuhi
following = berikut ini / pengikut
food = makanan / pangan
foot = kaki / ukuran kaki (30 cm)
football = sepak bola
for = untuk / selama / karena
force = kekuatan / memaksa / pasukan
foreign = asing / luar negeri
forest = hutan
forever = selamanya / abadi
forget = lupa / melupakan
form = bentuk / formulir / membentuk
formal = formal / resmi
formation = formasi / pembentukan
former = mantan / bekas / yang terdahulu
formula = formula / rumus / susu formula
forth = ke depan / keluar
fortune = keberuntungan / kekayaan / nasib
forward = maju / ke depan / meneruskan
found = menemukan (lampau) / mendirikan
foundation = yayasan / fondasi / dasar
founder = pendiri
four = empat
fourth = keempat
frame = bingkai / kerangka / menjebak
framework = kerangka kerja
free = gratis / bebas / membebaskan
freedom = kebebasan / kemerdekaan
freeze = membeku / membekukan
frequency = frekuensi / kekerapan
frequent = sering / kerap
frequently = sering kali
fresh = segar / baru
friend = teman / sahabat
friendly = ramah / bersahabat
friendship = persahabatan / pertemanan
from = dari / sejak
front = depan / bagian depan
fruit = buah
frustration = frustrasi / kekecewaan
fuel = bahan bakar / memicu
full = penuh / kenyang / lengkap
fully = sepenuhnya / secara lengkap
fun = kesenangan / menyenangkan
function = fungsi / berfungsi / acara
fund = dana / mendanai
fundamental = fundamental / mendasar
funding = pendanaan / pembiayaan
funeral = pemakaman
funny = lucu / aneh
furniture = perabotan / mebel
furthermore = selain itu / lebih lanjut
future = masa depan / yang akan datang
gain = mendapatkan / keuntungan / bertambah
galaxy = galaksi
gallery = galeri / balai seni
game = permainan / pertandingan
gang = geng / gerombolan
gap = celah / kesenjangan
garage = garasi / bengkel
garden = taman / kebun
garlic = bawang putih
gas = gas / bensin
gate = gerbang / pintu air
gather = mengumpulkan / berkumpul
gay = gay / ceria
gaze = menatap / tatapan
gear = gigi mesin / perlengkapan
gender = gender / jenis kelamin
gene = gen
general = umum / jenderal
generally = umumnya / biasanya
generate = menghasilkan / membangkitkan
generation = generasi / pembangkitan
genetic = genetik / keturunan
gentleman = pria terhormat / tuan
gently = dengan lembut / perlahan
gesture = gerakan tubuh / isyarat
get = mendapatkan / menjadi / tiba
ghost = hantu / roh
giant = raksasa / sangat besar
gift = hadiah / bakat
gifted = berbakat / cerdas
girl = anak perempuan / gadis
girlfriend = pacar perempuan / teman wanita
give = memberi / memberikan
given = diberikan / mengingat / tertentu
glad = senang / gembira
glance = melirik / sekilas
glass = kaca / gelas
global = global / mendunia
glove = sarung tangan
go = pergi / berangkat / berjalan
goal = tujuan / gol / sasaran
god = tuhan / dewa
gold = emas
golden = keemasan / terbuat dari emas
golf = golf
good = baik / bagus / barang
government = pemerintah / pemerintahan
governor = gubernur
grab = meraih / mengambil / merebut
grade = nilai / kelas / tingkat
gradually = secara bertahap / perlahan-lahan
graduate = lulus / lulusan / sarjana
grain = biji-bijian / butir / gandum
grand = agung / megah / besar
grandfather = kakek
grandmother = nenek
grant = hibah / mengabulkan / memberikan
grass = rumput
grave = kuburan / makam / serius
gray = abu-abu / mendung
great = hebat / besar / bagus sekali
greatest = terbesar / terhebat
green = hijau / ramah lingkungan
grocery = bahan makanan / toko kelontong
ground = tanah / dasar / alasan
group = kelompok / grup / mengelompokkan
grow = tumbuh / berkembang / menanam
growing = berkembang / meningkat
growth = pertumbuhan / perkembangan
guarantee = jaminan / menjamin
guard = penjaga / menjaga / pelindung
guess = menebak / tebakan / kira
guest = tamu
guide = pemandu / panduan / membimbing
guideline = pedoman / garis besar
guilty = bersalah / merasa bersalah
gun = senjata api / pistol
guy = pria / orang / teman-teman
habit = kebiasaan
habitat = habitat / tempat tinggal alami
hair = rambut / bulu
half = setengah / separuh
hall = aula / lorong
hand = tangan / menyerahkan / membantu
handful = segenggam / sedikit
handle = menangani / pegangan / gagang
hang = menggantung / bersantai
happen = terjadi / kebetulan
happy = bahagia / senang
hard = keras / sulit / giat
hardly = hampir tidak / baru saja
hat = topi
hate = benci / membenci
have = memiliki / mempunyai / harus
he = dia (laki-laki)
head = kepala / memimpin / menuju
headline = judul berita utama
headquarters = markas besar / kantor pusat
health = kesehatan
healthy = sehat / menyehatkan
hear = mendengar / mendengarkan
hearing = pendengaran / sidang pengadilan
heart = jantung / hati
heat = panas / memanaskan
heaven = surga / langit
heavily = dengan berat / sangat
heavy = berat / lebat / padat
heel = tumit / hak sepatu
height = tinggi / ketinggian / puncak
helicopter = helikopter
hell = neraka
hello = halo
help = membantu / bantuan / tolong
helpful = bermanfaat / suka membantu
her = dia / miliknya (perempuan)
here = di sini / ke sini
heritage = warisan / pusaka
hero = pahlawan / tokoh utama
herself = dirinya sendiri (perempuan)
hey = hai / hei
hi = hai / halo
hide = bersembunyi / menyembunyikan
high = tinggi / tingkat tinggi
highlight = sorotan / menyoroti / bagian terbaik
highly = sangat / dengan tingkat tinggi
highway = jalan raya / jalan tol
hill = bukit
him = dia (laki-laki, objek)
himself = dirinya sendiri (laki-laki)
hip = pinggul / keren
hire = mempekerjakan / menyewa
his = miliknya (laki-laki)
historian = sejarawan / ahli sejarah
historic = bersejarah / penting dalam sejarah
historical = historis / berkaitan dengan sejarah
history = sejarah / riwayat
hit = memukul / menabrak / pukulan / populer
hold = memegang / menahan / mengadakan
hole = lubang / celah
holiday = hari libur / liburan
holy = suci / kudus
home = rumah / pulang / kampung halaman
homeless = tunawisma / tidak punya rumah
honest = jujur / tulus
honey = madu / sayang
honor = kehormatan / menghormati / penghargaan
hope = harapan / berharap
horizon = cakrawala / batas pandangan
horror = horor / kengerian
horse = kuda
hospital = rumah sakit
host = tuan rumah / pembawa acara / menjamu
hot = panas / pedas / populer
hotel = hotel
hour = jam
house = rumah / menampung
household = rumah tangga
housing = perumahan / tempat tinggal
how = bagaimana / betapa / berapa
however = namun / akan tetapi / bagaimanapun
huge = sangat besar / raksasa
human = manusia / manusiawi
humor = humor / kejenakaan
hundred = ratus / seratus
hungry = lapar
hunter = pemburu
hunting = berburu / perburuan
hurt = menyakiti / terluka / sakit
husband = suami
hypothesis = hipotesis / dugaan sementara
I = saya / aku
ice = es
idea = ide / gagasan / pikiran
ideal = ideal / sempurna
identification = identifikasi / tanda pengenal
identify = mengidentifikasi / mengenali
identity = identitas / jati diri
ignore = mengabaikan / tidak memedulikan
ill = sakit / buruk
illegal = ilegal / tidak sah / melanggar hukum
illness = penyakit / keadaan sakit
illustrate = mengilustrasikan / menggambarkan
image = gambar / citra / bayangan
imagination = imajinasi / daya khayal
imagine = membayangkan / mengira
immediate = segera / langsung
immediately = dengan segera / langsung
immigrant = imigran / pendatang
immigration = imigrasi
impact = dampak / pengaruh / benturan
implement = menerapkan / melaksanakan / alat
implication = implikasi / keterlibatan / dampak
imply = menyiratkan / mengisyaratkan
importance = pentingnya / arti penting
important = penting / berarti
impose = memaksakan / mengenakan (pajak/hukuman)
impossible = tidak mungkin / mustahil
impress = mengesankan / membuat kagum
impression = kesan / impresi
impressive = mengesankan / hebat
improve = meningkatkan / memperbaiki / membaik
improvement = peningkatan / perbaikan
in = di dalam / di / pada
incentive = insentif / dorongan
incident = insiden / kejadian / peristiwa
include = termasuk / mencakup / memasukkan
including = termasuk / mencakup
income = pendapatan / penghasilan
incorporate = menggabungkan / memasukkan
increase = meningkatkan / bertambah / kenaikan
increased = meningkat / bertambah
increasing = semakin meningkat
increasingly = semakin / kian
incredible = luar biasa / sulit dipercaya
indeed = memang / sungguh
independence = kemerdekaan / kemandirian
independent = mandiri / merdeka / independen
index = indeks / daftar / petunjuk
indicate = menunjukkan / mengindikasikan
indication = indikasi / petunjuk / tanda
individual = individu / perorangan / pribadi
industrial = industri / bersifat industri
industry = industri / kerajinan
infant = bayi / anak kecil
infection = infeksi / penularan
inflation = inflasi
influence = pengaruh / memengaruhi
inform = menginformasikan / memberitahu
information = informasi / keterangan
ingredient = bahan / bumbu
initial = awal / inisial / paraf
initially = pada awalnya / mula-mula
initiative = inisiatif / prakarsa
injury = cedera / luka
inner = bagian dalam / batin
innocent = tidak bersalah / polos
inquiry = penyelidikan / pertanyaan
inside = di dalam / bagian dalam
insight = wawasan / pemahaman mendalam
insist = bersikeras / mendesak
inspire = menginspirasi / mengilhami
install = memasang / menginstal
instance = contoh / kejadian
instead = sebagai gantinya / malah
institution = institusi / lembaga
institutional = kelembagaan
instruction = instruksi / petunjuk / pengajaran
instructor = instruktur / pelatih
instrument = instrumen / alat musik / alat
insurance = asuransi / jaminan
intellectual = intelektual / cendekiawan
intelligence = kecerdasan / intelijen
intend = berniat / bermaksud
intense = intens / sangat kuat / hebat
intensity = intensitas / kekuatan
intention = niat / maksud / tujuan
interaction = interaksi / hubungan timbal balik
interest = minat / bunga (bank) / kepentingan
interested = tertarik / berminat
interesting = menarik
internal = internal / bagian dalam
international = internasional / antarbangsa
Internet = internet
interpret = menafsirkan / menerjemahkan
interpretation = interpretasi / penafsiran
intervention = intervensi / campur tangan
interview = wawancara / mewawancarai
into = ke dalam / menjadi
introduce = memperkenalkan / mengajukan
introduction = pengenalan / pengantar / pendahuluan
invasion = invasi / penyerbuan
invest = berinvestasi / menanam modal
investigate = menyelidiki / menginvestigasi
investigation = penyelidikan / investigasi
investigator = penyelidik / penyidik
investment = investasi / penanaman modal
investor = investor / penanam modal
invite = mengundang / mengajak
involve = melibatkan / mencakup
involved = terlibat / rumit
involvement = keterlibatan
iron = besi / setrika / menyetrika
island = pulau
issue = isu / masalah / menerbitkan / edisi
it = itu / ini (kata ganti benda/hewan)
item = barang / item / butir
its = miliknya (benda/hewan)
itself = dirinya sendiri (benda/hewan)
jacket = jaket / jas pendek
jail = penjara / memenjarakan
jet = pesawat jet / semburan
jewel = permata / batu mulia
jewelry = perhiasan
job = pekerjaan / tugas
join = bergabung / menyambung / ikut
joint = bersama / sendi / sambungan
joke = lelucon / bercanda
journal = jurnal / buku harian / majalah ilmiah
journalist = jurnalis / wartawan
journey = perjalanan / pengembaraan
joy = kegembiraan / sukacita
judge = hakim / menilai / menghakimi
judgment = penilaian / keputusan pengadilan
juice = jus / sari buah
jump = melompat / lompatan / melonjak
junior = junior / lebih muda / bawahan
jury = juri / dewan juri
just = hanya / baru saja / adil
justice = keadilan / hakim agung
justify = membenarkan / membuktikan benar
keep = menjaga / menyimpan / tetap
key = kunci / utama / tombol
kick = menendang / tendangan
kid = anak-anak / bercanda
kill = membunuh / mematikan
killer = pembunuh
killing = pembunuhan
kind = jenis / macam / baik hati
king = raja
kiss = mencium / ciuman
kitchen = dapur
knee = lutut
knife = pisau
knock = mengetuk / ketukan / memukul
know = tahu / mengetahui / mengenal
knowledge = pengetahuan / ilmu
lab = laboratorium
label = label / merek / memberi label
labor = tenaga kerja / buruh / persalinan
laboratory = laboratorium
lack = kekurangan / tidak memiliki
lady = wanita / nyonya
lake = danau
land = tanah / daratan / mendarat
landscape = pemandangan alam / lanskap
language = bahasa
lap = pangkuan / putaran (lomba)
large = besar / luas
largely = sebagian besar / terutama
last = terakhir / lalu / bertahan
late = terlambat / larut / almarhum
later = nanti / kemudian
latter = yang disebut terakhir
laugh = tertawa / tawa
launch = meluncurkan / peluncuran
law = hukum / undang-undang
lawn = halaman rumput
lawsuit = gugatan hukum / tuntutan
lawyer = pengacara / ahli hukum
lay = meletakkan / berbaring / bertelur
layer = lapisan / tingkat
lead = memimpin / mengarah / timah
leader = pemimpin / ketua
leadership = kepemimpinan
leading = terkemuka / utama
leaf = daun / lembaran
league = liga / persekutuan
lean = bersandar / condong / ramping / tanpa lemak
learn = belajar / mempelajari / mengetahui
learning = pembelajaran / ilmu pengetahuan
least = paling sedikit / terkecil
leather = kulit (bahan)
leave = meninggalkan / pergi / cuti
left = kiri / tersisa / pergi (lampau)
leg = kaki (dari paha ke bawah)
legacy = warisan / peninggalan
legal = legal / sah / hukum
legend = legenda / cerita rakyat
legislation = undang-undang / legislasi
legitimate = sah / resmi / wajar
lemon = lemon / jeruk sitrun
length = panjang / durasi
less = kurang / lebih sedikit
lesson = pelajaran / hikmah
let = membiarkan / mengizinkan / menyewakan
letter = surat / huruf
level = tingkat / level / datar
liberal = liberal / bebas / dermawan
library = perpustakaan
license = lisensi / izin / surat izin
lie = berbohong / bohong / berbaring / terletak
life = hidup / kehidupan / nyawa
lifestyle = gaya hidup
lifetime = seumur hidup / masa hidup
lift = mengangkat / tumpangan / lift
light = cahaya / terang / ringan / menyalakan
like = suka / seperti / mirip
likely = kemungkinan besar / mungkin
limit = batas / membatasi
limitation = batasan / keterbatasan
limited = terbatas
line = garis / antrean / baris / saluran
link = tautan / menghubungkan / hubungan
lip = bibir
list = daftar / mendaftar
listen = mendengarkan / menyimak
literally = secara harfiah / benar-benar
literary = sastra / berkaitan dengan karya tulis
literature = sastra / literatur / bacaan
little = kecil / sedikit
live = hidup / tinggal / siaran langsung
living = hidup / kehidupan / nafkah
load = muatan / beban / memuat
loan = pinjaman / meminjamkan
local = lokal / setempat / penduduk setempat
locate = menemukan lokasi / menempatkan
location = lokasi / tempat / letak
lock = kunci / mengunci
long = panjang / lama / merindukan
long-term = jangka panjang
look = melihat / tampak / penampilan
loose = longgar / lepas / bebas
lose = kehilangan / kalah
loss = kerugian / kehilangan / kekalahan
lost = hilang / tersesat / kalah (lampau)
lot = banyak / undian / lahan parkir
lots = banyak sekali
loud = keras / nyaring (suara)
love = cinta / mencintai / sangat suka
lovely = indah / menyenangkan / cantik
lover = kekasih / pecinta
low = rendah / pelan / murung
lower = menurunkan / lebih rendah
luck = keberuntungan / nasib baik
lucky = beruntung / mujur
lunch = makan siang
lung = paru-paru
machine = mesin / alat
mad = marah / gila
magazine = majalah
mail = surat / pos / mengirim surat
main = utama / pokok
mainly = terutama / sebagian besar
maintain = mempertahankan / merawat / menjaga
maintenance = pemeliharaan / perawatan / nafkah
major = utama / besar / jurusan kuliah / mayor
majority = mayoritas / sebagian besar
make = membuat / menjadikan / merek
maker = pembuat / pencipta
makeup = riasan wajah / susunan / sifat
male = laki-laki / jantan
mall = mal / pusat perbelanjaan
man = pria / laki-laki / manusia
manage = mengelola / mengatur / berhasil
management = manajemen / pengelolaan / pengurus
manager = manajer / pengelola
manner = cara / sikap / sopan santun
manufacturer = produsen / pabrik pembuat
manufacturing = manufaktur / pembuatan barang
many = banyak (untuk benda yang bisa dihitung)
map = peta / memetakan
margin = batas / tepi / selisih keuntungan
mark = tanda / nilai / menandai
market = pasar / memasarkan
marketing = pemasaran
marriage = pernikahan / perkawinan
married = menikah / sudah menikah
marry = menikah / menikahi
mask = topeng / masker / menutupi
mass = massa / jumlah besar / misa
massive = masif / sangat besar
master = tuan / ahli / menguasai / gelar master
match = pertandingan / cocok / korek api
material = bahan / materi / kain
math = matematika
matter = masalah / materi / penting
may = mungkin / boleh / bulan Mei
maybe = mungkin / barangkali
mayor = wali kota
me = saya / aku (sebagai objek)
meal = makanan / waktu makan
mean = berarti / maksud / jahat / rata-rata
meaning = arti / makna
meanwhile = sementara itu / dalam pada itu
measure = mengukur / ukuran / tindakan
measurement = pengukuran / ukuran
meat = daging
mechanism = mekanisme / cara kerja
media = media
medical = medis / kedokteran
medication = pengobatan / obat
medicine = obat / ilmu kedokteran
medium = sedang / media / perantara
meet = bertemu / memenuhi
meeting = pertemuan / rapat
member = anggota
membership = keanggotaan
memory = ingatan / kenangan / memori
mental = mental / batin / jiwa
mention = menyebutkan / menyebut
menu = menu / daftar pilihan
mere = hanya / belaka / semata
merely = hanya / semata-mata
mess = kekacauan / berantakan / mengacaukan
message = pesan / amanat
metal = logam
meter = meter / alat pengukur
method = metode / cara
middle = tengah / pertengahan
might = mungkin / kekuatan
military = militer / tentara
milk = susu / memerah susu
million = juta
mind = pikiran / keberatan / menjaga
mine = milikku / tambang / ranjau
minister = menteri / pendeta
minor = kecil / ringan / di bawah umur
minority = minoritas / kelompok kecil
minute = menit / sangat kecil / risalah rapat
miracle = keajaiban / mukjizat
mirror = cermin / mencerminkan
miss = rindu / kehilangan / ketinggalan / nona
missile = rudal / peluru kendali
mission = misi / tugas / utusan
mistake = kesalahan / kekeliruan
mix = mencampur / campuran
mixture = campuran / gabungan
mode = mode / cara
model = model / peraga / contoh
moderate = moderat / sedang / menahan diri
modern = modern / masa kini
modest = sederhana / rendah hati
mom = ibu / mama
moment = momen / saat / sebentar
money = uang
monitor = memantau / layar monitor
month = bulan (waktu)
mood = suasana hati / mood
moon = bulan (benda langit)
moral = moral / akhlak / pesan moral
more = lebih / lagi
moreover = selain itu / terlebih lagi
morning = pagi
mortgage = hipotek / KPR (Kredit Pemilikan Rumah)
most = paling / sebagian besar
mostly = kebanyakan / sebagian besar
mother = ibu
motion = gerakan / mosi / isyarat
motivation = motivasi / dorongan
motor = motor / mesin penggerak
mount = gunung / mendaki / memasang
mountain = gunung / pegunungan
mouse = tikus / tetikus (komputer)
mouth = mulut / muara sungai
move = bergerak / pindah / langkah
movement = gerakan / pergerakan
movie = film / bioskop
much = banyak (untuk benda tak terhitung) / sangat
multiple = banyak / berlipat ganda / kelipatan
murder = pembunuhan / membunuh
muscle = otot / kekuatan fisik
museum = museum
music = musik
musical = musikal / berkaitan dengan musik
musician = musisi / pemusik
must = harus / pasti
mutual = bersama / saling / timbal balik
my = milikku / ... saya
myself = diriku sendiri / saya sendiri
mystery = misteri / teka-teki
myth = mitos / dongeng
naked = telanjang / terbuka
name = nama / menamai / menunjuk
narrative = narasi / cerita
narrow = sempit / mempersempit / tipis
nation = bangsa / negara
national = nasional / kebangsaan
native = asli / pribumi / penutur asli
natural = alami / wajar
naturally = secara alami / tentu saja
nature = alam / sifat dasar
near = dekat / mendekati
nearby = di dekat sini / sekitar
nearly = hampir / nyaris
necessarily = belum tentu / harus / secara mutlak
necessary = perlu / penting / dibutuhkan
neck = leher / kerah
need = butuh / membutuhkan / kebutuhan
negative = negatif / menolak
negotiate = bernegosiasi / berunding
negotiation = negosiasi / perundingan
neighbor = tetangga
neighborhood = lingkungan sekitar / kompleks perumahan
neither = tidak keduanya / bukan salah satu
nerve = saraf / keberanian / nyali
nervous = gugup / cemas / gelisah
net = jaring / bersih (keuntungan/berat) / internet
network = jaringan / jejaring
never = tidak pernah
nevertheless = namun / meskipun demikian
new = baru
newly = baru saja / belum lama ini
news = berita / kabar
newspaper = koran / surat kabar
next = berikutnya / selanjutnya / di sebelah
nice = bagus / baik / menyenangkan
night = malam
nine = sembilan
no = tidak / bukan
nobody = tidak seorang pun / bukan siapa-siapa
nod = mengangguk / anggukan
noise = suara bising / keributan / kegaduhan
nomination = nominasi / pencalonan
none = tidak ada / tidak satu pun
nonetheless = meskipun demikian / namun
nor = maupun tidak / dan juga tidak
normal = normal / biasa
normally = biasanya / secara normal
north = utara
northern = bagian utara
nose = hidung / moncong
not = tidak / bukan
note = catatan / mencatat / nada / uang kertas
nothing = tidak ada / bukan apa-apa
notice = memperhatikan / pemberitahuan / pengumuman
notion = gagasan / ide / anggapan
novel = novel / baru / unik
now = sekarang / saat ini
nowhere = tidak di mana pun / tidak ke mana-mana
nuclear = nuklir
number = nomor / angka / jumlah
numerous = banyak sekali / berjumlah banyak
nurse = perawat / merawat / menyusui
nut = kacang / mur (baut) / orang gila
object = objek / benda / menolak / keberatan
objective = tujuan / sasaran / objektif
obligation = kewajiban / keharusan
observation = pengamatan / observasi
observe = mengamati / memperhatikan / mematuhi
observer = pengamat / peninjau
obtain = memperoleh / mendapatkan
obvious = jelas / nyata / gamblang
obviously = jelas sekali / tentu saja
occasion = kesempatan / acara / waktu tertentu
occasionally = kadang-kadang / sesekali
occupation = pekerjaan / jabatan / pendudukan
occupy = menempati / menduduki / menyibukkan
occur = terjadi / muncul dalam pikiran
ocean = samudra / lautan
odd = aneh / ganjil
odds = peluang / kemungkinan / rintangan
of = dari / tentang / milik
off = mati (listrik) / lepas / libur / jauh
offense = pelanggaran / kejahatan / penyerangan
offensive = menyinggung / menyerang / serangan
offer = menawarkan / tawaran
office = kantor / jabatan
officer = petugas / perwira / pejabat
official = resmi / pejabat
often = sering / kerap
oh = oh (kata seru)
oil = minyak / oli / meminyaki
ok = oke / baik-baik saja / menyetujui
okay = oke / baiklah / setuju
old = tua / lama
olympic = olimpiade
on = di atas / menyala / pada / tentang
once = sekali / pernah / segera setelah
one = satu / seseorang
ongoing = sedang berlangsung / terus berjalan
onion = bawang bombay / bawang
online = daring / online / terhubung internet
only = hanya / satu-satunya / cuma
onto = ke atas / ke
open = buka / membuka / terbuka
opening = pembukaan / celah / lowongan kerja
operate = beroperasi / mengoperasikan / membedah
operating = pengoperasian / operasional
operation = operasi / kegiatan / pembedahan
operator = operator / pengelola
opinion = opini / pendapat / pandangan
opponent = lawan / penentang
opportunity = kesempatan / peluang
oppose = menentang / melawan
opposite = berlawanan / seberang / kebalikan
opposition = oposisi / perlawanan / pertentangan
option = opsi / pilihan
or = atau
orange = jeruk / warna oranye
order = pesanan / perintah / urutan / memesan
ordinary = biasa / umum / lumrah
organic = organik / alami
organization = organisasi / lembaga / pengaturan
organize = mengatur / mengorganisir / menyelenggarakan
orientation = orientasi / pengenalan / arah
origin = asal / asal-usul / sumber
original = asli / orisinal / awal
originally = awalnya / semula / aslinya
other = lain / yang lain
others = yang lainnya / orang lain
otherwise = jika tidak / sebaliknya / dengan cara lain
ought = seharusnya / sebaiknya
our = milik kita / milik kami
ourselves = diri kita sendiri / diri kami sendiri
out = keluar / di luar / habis / padam
outcome = hasil / akibat / kesudahan
outside = di luar / bagian luar
oven = oven / pemanggang
over = di atas / selesai / lebih dari / melewati
overall = secara keseluruhan / total
overcome = mengatasi / menaklukkan
overlook = mengabaikan / menghadap ke (pemandangan)
owe = berutang / wajib memberikan
own = sendiri / memiliki / mengakui
owner = pemilik
pace = langkah / kecepatan / mengatur langkah
pack = pak / bungkus / mengemas / kawanan
package = paket / kemasan / membungkus
page = halaman / memanggil
pain = rasa sakit / nyeri / penderitaan
painful = menyakitkan / perih
paint = cat / mengecat / melukis
painter = pelukis / tukang cat
painting = lukisan / pengecatan
pair = pasangan / sepasang / memasangkan
pale = pucat / pudar
pan = wajan / panci datar
panel = panel / dewan juri / diskusi panel
pant = celana / terengah-engah
paper = kertas / koran / makalah
parent = orang tua (ayah/ibu)
park = taman / memarkir
parking = parkir / tempat parkir
part = bagian / peran / berpisah
participant = peserta / partisipan
participate = berpartisipasi / ikut serta
participation = partisipasi / keikutsertaan
particular = tertentu / khusus / cerewet
particularly = khususnya / terutama
partly = sebagian / tidak sepenuhnya
partner = pasangan / mitra / rekan
partnership = kemitraan / kerja sama / persekutuan
party = pesta / partai / pihak
pass = melewati / lulus / mengoper / kartu izin
passage = lorong / kutipan bacaan / perjalanan
passenger = penumpang
passion = gairah / semangat / hasrat
past = masa lalu / lewat / melewati
patch = tambalan / menambal / sebidang tanah
path = jalan setapak / jalur / lintasan
patient = pasien / sabar
pattern = pola / corak / motif
pause = jeda / berhenti sebentar
pay = membayar / gaji / upah
payment = pembayaran
peace = perdamaian / ketenangan
peak = puncak / tertinggi
peer = rekan sebaya / menatap dengan saksama
penalty = hukuman / denda / penalti
people = orang-orang / rakyat / bangsa
pepper = lada / merica / cabai / paprika
per = per / setiap / melalui
perceive = melihat / memahami / menganggap
percentage = persentase
perception = persepsi / pandangan / tanggapan
perfect = sempurna / menyempurnakan
perfectly = dengan sempurna / sepenuhnya
perform = tampil / melakukan / menjalankan
performance = penampilan / kinerja / pertunjukan
perhaps = mungkin / barangkali
period = periode / masa / titik / menstruasi
permanent = permanen / tetap / abadi
permission = izin / persetujuan
permit = mengizinkan / surat izin
person = orang / individu / pribadi
personal = pribadi / personal
personality = kepribadian / karakter / tokoh
personally = secara pribadi / menurut saya
personnel = personel / staf / kepegawaian
perspective = perspektif / sudut pandang
persuade = membujuk / meyakinkan
pet = hewan peliharaan / kesayangan / mengelus
phase = fase / tahap / babak
phenomenon = fenomena / gejala / keajaiban
philosophy = filsafat / filosofi / pandangan hidup
phone = telepon / menelepon
photo = foto
photograph = foto / memotret
photographer = fotografer / juru foto
phrase = frasa / ungkapan / mengungkapkan
physical = fisik / jasmani
physically = secara fisik
physician = dokter / tabib
piano = piano
pick = memilih / memetik / menjemput
picture = gambar / foto / membayangkan
pie = kue pai
piece = potongan / bagian / karya
pile = tumpukan / menumpuk
pilot = pilot / memandu / uji coba
pine = pohon pinus / merindukan
pink = merah muda
pipe = pipa / selang / pipa rokok
pitch = nada / melempar / lapangan / presentasi bisnis
place = tempat / menempatkan / meletakkan
plan = rencana / merencanakan / denah
plane = pesawat terbang / bidang datar
planet = planet
planning = perencanaan
plant = tanaman / menanam / pabrik
plastic = plastik
plate = piring / pelat / melapisi logam
platform = platform / peron / panggung
play = bermain / memutar / drama / lakon
player = pemain / pemutar (media)
please = tolong / silakan / menyenangkan
pleasure = kesenangan / kenikmatan / kehormatan
plenty = banyak / berlimpah
plot = alur cerita / komplotan / sebidang tanah
plus = tambah / ditambah / kelebihan
pocket = saku / kantong / mengantongi
poem = puisi / sajak
poet = penyair / pujangga
poetry = puisi / karya sastra puisi
point = titik / poin / menunjuk / tujuan
pole = kutub / tiang / galah
police = polisi / menjaga ketertiban
policy = kebijakan / polis asuransi
political = politik / politis
politically = secara politik
politician = politisi / politikus
politics = politik / ilmu politik
poll = jajak pendapat / pemungutan suara
pollution = polusi / pencemaran
pool = kolam / mengumpulkan bersama / biliar
poor = miskin / buruk / malang
pop = musik pop / meletus / muncul tiba-tiba
popular = populer / terkenal / disukai banyak orang
population = populasi / penduduk
porch = beranda / teras
port = pelabuhan / lubang koneksi (komputer)
portion = porsi / bagian
portrait = potret / lukisan wajah
portray = menggambarkan / memerankan
pose = berpose / gaya / menimbulkan (masalah)
position = posisi / jabatan / letak / menempatkan
positive = positif / yakin / pasti
possess = memiliki / mempunyai / merasuki
possibility = kemungkinan / peluang
possible = mungkin / bisa terjadi
possibly = mungkin / barangkali / sama sekali
post = pos / tiang / jabatan / mengirim / mengunggah
pot = panci / pot / teko
potato = kentang
potential = potensi / potensial / kemungkinan
potentially = secara potensial / kemungkinan besar
pound = pon (ukuran berat) / mata uang pound / memukul keras
pour = menuangkan / mengalir deras (hujan)
poverty = kemiskinan
powder = bubuk / bedak
power = kekuatan / kekuasaan / listrik / tenaga
powerful = kuat / berkuasa / berpengaruh
practical = praktis / berguna / nyata
practice = latihan / praktik / berlatih
pray = berdoa / memohon
prayer = doa / sembahyang
precisely = tepatnya / persis / dengan tepat
predict = memprediksi / meramalkan
prefer = lebih suka / memilih
preference = preferensi / pilihan utama / kesukaan
pregnancy = kehamilan
pregnant = hamil / mengandung
preparation = persiapan
prepare = menyiapkan / mempersiapkan / bersiap
prescription = resep dokter
presence = kehadiran / keberadaan / wibawa
present = hadir / hadiah / saat ini / menyajikan
presentation = presentasi / penyajian / pemberian
preserve = melestarikan / menjaga / mengawetkan
president = presiden / direktur utama / ketua
presidential = kepresidenan
press = menekan / pers (media) / mesin cetak
pressure = tekanan / menekan / desakan
pretend = berpura-pura / berdalih
pretty = cantik / cukup / lumayan
prevent = mencegah / menghalangi
previous = sebelumnya / terdahulu
previously = sebelumnya / dulunya
price = harga / biaya
pride = kebanggaan / harga diri / kawanan singa
priest = pendeta / pastor / imam
primarily = terutama / khususnya / pada awalnya
primary = utama / dasar / pokok
prime = utama / terbaik / masa kejayaan
principal = kepala sekolah / utama / modal pokok
principle = prinsip / asas / dasar
print = mencetak / cetakan / huruf cetak
prior = sebelumnya / lebih dulu / lebih penting
priority = prioritas / yang didahulukan
prison = penjara / lembaga pemasyarakatan
prisoner = tahanan / narapidana / tawanan
privacy = privasi / kerahasiaan pribadi
private = pribadi / swasta / tertutup
probably = mungkin / kemungkinan besar
problem = masalah / persoalan / soal
procedure = prosedur / tata cara / tindakan medis
proceed = melanjutkan / bergerak maju / hasil penjualan
process = proses / memproses / mengolah
produce = menghasilkan / memproduksi / hasil bumi
producer = produsen / produser
product = produk / hasil
production = produksi / pembuatan / pementasan
profession = profesi / pekerjaan / keahlian
professional = profesional / ahli / tenaga ahli
professor = profesor / guru besar
profile = profil / biodata singkat / tampak samping
profit = keuntungan / laba / bermanfaat
program = program / acara / memprogram
progress = kemajuan / perkembangan / bergerak maju
project = proyek / memproyeksikan / merencanakan
prominent = terkemuka / menonjol / terkenal
promise = janji / berjanji / harapan baik
promote = mempromosikan / mendukung / menaikkan jabatan
prompt = cepat / tepat waktu / mendorong / petunjuk
proof = bukti / tahan terhadap (misal: tahan air)
proper = tepat / layak / pantas / sopan
properly = dengan benar / dengan layak
property = properti / harta benda / sifat khas
proportion = proporsi / perbandingan / bagian
proposal = proposal / usulan / lamaran nikah
propose = mengusulkan / mengajukan / melamar
proposed = yang diusulkan / yang direncanakan
prosecutor = jaksa penuntut umum
prospect = prospek / harapan / calon pelanggan
protect = melindungi / menjaga
protection = perlindungan / proteksi
protein = protein
protest = protes / memprotes / unjuk rasa
proud = bangga / sombong
prove = membuktikan / ternyata
provide = menyediakan / memberikan / memberi nafkah
provider = penyedia / pemberi nafkah
province = provinsi / wilayah / bidang keahlian
provision = penyediaan / ketentuan / bekal
psychological = psikologis / kejiwaan
psychologist = psikolog / ahli kejiwaan
psychology = psikologi / ilmu jiwa
public = publik / umum / masyarakat
publication = publikasi / penerbitan / terbitan
publicly = secara terbuka / di depan umum
publish = menerbitkan / memublikasikan
publisher = penerbit
pull = menarik / tarikan / mencabut
punishment = hukuman / sanksi
purchase = membeli / pembelian / barang belian
pure = murni / bersih / suci
purpose = tujuan / maksud / kegunaan
pursue = mengejar / melanjutkan / menekuni
push = mendorong / dorongan / menekan
put = meletakkan / menaruh / menempatkan
qualify = memenuhi syarat / lolos kualifikasi
quality = kualitas / mutu / sifat
quarter = seperempat / kuartal / 15 menit / wilayah
quarterback = posisi pengumpan (dalam sepak bola Amerika)
question = pertanyaan / mempertanyakan / masalah
quick = cepat / singkat / tangkas
quickly = dengan cepat / segera
quiet = tenang / diam / sunyi
quietly = dengan tenang / diam-diam
quit = berhenti / keluar / meninggalkan
quite = cukup / lumayan / sepenuhnya
quote = kutipan / mengutip / memberikan harga
race = balapan / ras (suku bangsa) / berlomba
racial = rasial / berkaitan dengan ras
radical = radikal / mendasar / ekstrem
radio = radio
rail = rel / pagar pembatas
rain = hujan / turun hujan
raise = menaikkan / mengangkat / membesarkan (anak) / kenaikan gaji
range = rentang / jangkauan / deretan / berkisar
rank = peringkat / pangkat / memberi peringkat
rapid = cepat / pesat / deras
rapidly = dengan cepat / secara pesat
rare = langka / jarang / setengah matang (daging)
rarely = jarang / hampir tidak pernah
rate = tingkat / tarif / kecepatan / menilai
rather = agak / lebih baik / melainkan
rating = peringkat / penilaian
ratio = rasio / perbandingan
raw = mentah / belum diolah / lecet
reach = mencapai / meraih / jangkauan
react = bereaksi / menanggapi
reaction = reaksi / tanggapan
read = membaca
reader = pembaca
reading = membaca / bacaan
ready = siap / sedia
real = nyata / asli / sungguhan
reality = realitas / kenyataan
realize = menyadari / mewujudkan
really = benar-benar / sungguh / sangat
reason = alasan / akal / berpikir logis
reasonable = masuk akal / wajar / terjangkau
recall = mengingat kembali / menarik kembali (produk/pejabat)
receive = menerima / mendapatkan
recent = baru-baru ini / terkini
recently = baru-baru ini / belakangan ini
recipe = resep masakan / cara mencapai sesuatu
recognition = pengakuan / penghargaan / pengenalan
recognize = mengenali / mengakui / menghargai
recommend = merekomendasikan / menyarankan
recommendation = rekomendasi / saran / anjuran
record = catatan / rekor / merekam / piringan hitam
recording = rekaman / perekaman
recover = pulih / sembuh / menemukan kembali
recovery = pemulihan / kesembuhan / penemuan kembali
recruit = merekrut / anggota baru / tulok
red = merah
reduce = mengurangi / menurunkan / mereduksi
reduction = pengurangan / penurunan / potongan harga
refer = merujuk / mengacu / menyerahkan
reference = referensi / rujukan / surat rekomendasi
reflect = mencerminkan / memantulkan / merenungkan
reflection = bayangan / pantulan / renungan / cerminan
reform = reformasi / pembaruan / memperbaiki
refugee = pengungsi
refuse = menolak / sampah
regard = menganggap / memperhatikan / salam / hormat
regarding = mengenai / tentang / perihal
regardless = tanpa memedulikan / bagaimanapun juga
regime = rezim / pemerintahan / aturan pola hidup
region = wilayah / daerah / kawasan
regional = regional / kedaerahan
register = mendaftar / daftar / kasir
regular = teratur / biasa / reguler / pelanggan tetap
regularly = secara teratur / rutin
regulate = mengatur / mengendalikan / menertibkan
regulation = peraturan / regulasi / pengaturan
reinforce = memperkuat / mempertegas / menambah pasukan
reject = menolak / membuang / barang afkir
relate = berhubungan / menceritakan / memahami perasaan
related = terkait / berhubungan / bersaudara
relation = hubungan / relasi / kerabat
relationship = hubungan / ikatan / pacaran
relative = kerabat / saudara / relatif (nisbi)
relatively = secara relatif / cukup / lumayan
relax = bersantai / tenang / mengendurkan
release = merilis / melepaskan / pembebasan / peluncuran
relevant = relevan / sesuai / berkaitan
relief = kelegaan / bantuan (bencana) / keringanan
religion = agama / kepercayaan
religious = religius / keagamaan / taat beragama
rely = mengandalkan / bergantung / percaya
remain = tetap / tinggal / tersisa
remaining = yang tersisa / selebihnya
remarkable = luar biasa / menakjubkan / patut diperhatikan
remember = ingat / mengingat / mengenang
remind = mengingatkan
remote = terpencil / jauh / pengendali jarak jauh (remot)
remove = menghapus / menghilangkan / memindahkan / melepas
repeat = mengulangi / mengulang / ulangan
repeatedly = berulang kali / berkali-kali
replace = mengganti / menggantikan / mengembalikan ke tempat semula
reply = membalas / menjawab / balasan
report = laporan / melaporkan / memberitakan
reporter = reporter / wartawan
represent = mewakili / melambangkan / menggambarkan
representation = perwakilan / representasi / gambaran
representative = wakil / perwakilan / mencerminkan
republic = republik
reputation = reputasi / nama baik
request = permintaan / meminta / memohon
require = membutuhkan / memerlukan / mewajibkan
requirement = persyaratan / kebutuhan / syarat
research = penelitian / riset / meneliti
researcher = peneliti / periset
resemble = menyerupai / mirip dengan
reservation = reservasi / pemesanan tempat / keraguan / cagar alam
resident = penduduk / penghuni / dokter residen
resist = menolak / menahan / melawan
resistance = perlawanan / ketahanan / hambatan
resolution = resolusi / keputusan / penyelesaian / ketajaman layar
resolve = menyelesaikan / memutuskan / tekad bulat
resort = resor / tempat liburan / jalan terakhir / mengambil langkah
resource = sumber daya / akal / sarana
respect = hormat / menghormati / menghargai / aspek
respond = merespons / menanggapi / menjawab
respondent = responden / penjawab kuesioner
response = respons / tanggapan / jawaban
responsibility = tanggung jawab / kewajiban
responsible = bertanggung jawab / menjadi penyebab
rest = istirahat / beristirahat / sisa / yang lainnya
restaurant = restoran / rumah makan
restore = memulihkan / mengembalikan / memperbaiki
restriction = pembatasan / larangan / batasan
result = hasil / akibat / berakibat
retain = mempertahankan / menyimpan / menyewa (pengacara)
retire = pensiun / mengundurkan diri / pergi tidur
retirement = masa pensiun / pengunduran diri
return = kembali / mengembalikan / keuntungan / kepulangan
reveal = mengungkapkan / membocorkan / memperlihatkan
revenue = pendapatan / penghasilan negara
review = ulasan / meninjau / memeriksa kembali
revolution = revolusi / perputaran
rhythm = ritme / irama
rice = beras / nasi / padi
rich = kaya / subur / pekat (rasa/warna)
rid = membebaskan / menyingkirkan
ride = mengendarai / tumpangan / wahana permainan
rifle = senapan laras panjang
right = benar / kanan / hak / langsung
ring = cincin / berdering / lingkaran / gelanggang (tinju)
rise = naik / bangkit / terbit / kenaikan
risk = risiko / mempertaruhkan / bahaya
river = sungai
road = jalan / jalur
rock = batu / musik rock / bergoyang
role = peran / tugas
roll = menggulung / berguling / gulungan / daftar nama / roti kecil
romantic = romantis / penuh cinta
roof = atap
room = ruangan / kamar / ruang kosong
root = akar / sumber / mendukung
rope = tali tambang / mengikat dengan tali
rose = bunga mawar / warna merah muda / naik (lampau dari rise)
rough = kasar / berat / kira-kira / bergelombang
roughly = kira-kira / secara kasar / dengan kasar
round = bulat / bundar / putaran / babak / mengelilingi
route = rute / jalur / jalan
routine = rutin / rutinitas / kebiasaan sehari-hari
row = baris / deretan / mendayung / pertengkaran
rub = menggosok / mengusap / pijatan
rule = aturan / peraturan / memerintah / menguasai
run = berlari / menjalankan / mengelola / mengalir
running = berlari / pengelolaan / berturut-turut
rural = pedesaan / luar kota
rush = terburu-buru / menyerbu / kesibukan
sacred = suci / keramat / sakral
sad = sedih / menyedihkan
safe = aman / brankas
safety = keamanan / keselamatan
sake = demi / kepentingan / tujuan
salad = salad / selada
salary = gaji / upah tetap
sale = penjualan / obral / diskon
sales = penjualan / bagian penjualan
salt = garam / menggarami
same = sama / serupa
sample = sampel / contoh / mencicipi
sanction = sanksi / hukuman / persetujuan resmi
sand = pasir
satellite = satelit / pengikut
satisfaction = kepuasan / pemenuhan
satisfy = memuaskan / memenuhi (syarat)
sauce = saus / kuah kental
save = menyimpan / menyelamatkan / menghemat / kecuali
saving = tabungan / penghematan / penyelamatan
say = mengatakan / berkata / ucap
scale = skala / timbangan / sisik / memanjat
scandal = skandal / aib / perkara memalukan
scared = takut / ketakutan
scenario = skenario / alur cerita / kemungkinan situasi
scene = adegan / pemandangan / tempat kejadian
schedule = jadwal / menjadwalkan
scheme = skema / rencana / rancangan / bersekongkol
scholar = sarjana / cendekiawan / penerima beasiswa
scholarship = beasiswa / ilmu pengetahuan
school = sekolah / menyekolahkan / kawanan ikan
science = sains / ilmu pengetahuan
scientific = ilmiah / secara keilmuan
scientist = ilmuwan / ahli sains
scope = cakupan / ruang lingkup / jangkauan
score = skor / nilai / mencetak gol / dua puluh
scream = berteriak / menjerit / teriakan
screen = layar / menyaring / sekat
script = naskah / skrip / tulisan tangan
sea = laut / lautan
search = mencari / pencarian / menggeledah
season = musim / membumbui masakan
seat = kursi / tempat duduk / mendudukkan
second = kedua / detik / mendukung usulan
secret = rahasia / merahasiakan
secretary = sekretaris / menteri
section = bagian / seksi / bab / irisan
sector = sektor / bidang / wilayah
secure = aman / mengamankan / mendapatkan
security = keamanan / sekuritas / jaminan
see = melihat / mengerti / mengunjungi
seed = benih / biji / bibit
seek = mencari / meminta / berusaha mendapatkan
seem = tampak / kelihatannya / rasanya
segment = segmen / bagian / ruas
seize = merebut / menyita / menangkap / memanfaatkan
select = memilih / pilihan / terpilih
selection = seleksi / pemilihan / pilihan barang
self = diri / diri sendiri / pribadi
sell = menjual / laku
senate = senat / dewan perwakilan
senator = senator / anggota senat
send = mengirim / mengutus / menyuruh
senior = senior / lebih tua / tingkat akhir
sense = indra / perasaan / arti / masuk akal / merasakan
sensitive = sensitif / peka / mudah tersinggung
sentence = kalimat / hukuman / menjatuhkan vonis
separate = terpisah / memisahkan / tersendiri
sequence = urutan / rangkaian / rentetan
series = seri / rangkaian / serial TV
serious = serius / parah / sungguh-sungguh
seriously = dengan serius / sungguh / parah
servant = pelayan / pembantu / abdi
serve = melayani / menyajikan / bertugas / menjalani hukuman
service = layanan / jasa / servis / kebaktian
session = sesi / sidang / masa pertemuan
set = mengatur / menetapkan / perangkat / terbenam
setting = pengaturan / latar tempat/waktu
settle = menyelesaikan / menetap / menenangkan / membayar
settlement = penyelesaian / pemukiman / kesepakatan
seven = tujuh
several = beberapa
severe = parah / keras / berat / kejam
sex = jenis kelamin / seks
sexual = seksual / berkaitan dengan jenis kelamin
shade = bayangan / tempat teduh / corak warna / tirai
shadow = bayangan / membayangi / mengikuti diam-diam
shake = menggoyangkan / bergetar / berjabat tangan / kocok
shall = akan / harus
shape = bentuk / membentuk / kondisi fisik
share = berbagi / membagikan / bagian / saham
sharp = tajam / cerdas / tepat (waktu) / mendadak
she = dia (perempuan)
sheet = lembar / seprai / lapisan tipis
shelf = rak
shell = cangkang / kerang / peluru meriam / mengupas
shelter = tempat berlindung / penampungan / melindungi
shift = bergeser / perubahan / giliran kerja (shift)
shine = bersinar / bercahaya / menyemir
ship = kapal / mengirim barang
shirt = kemeja / baju
shit = kotoran / omong kosong / sial (umpatan)
shock = kejutan / guncangan / membuat terkejut / tersetrum
shoe = sepatu
shoot = menembak / memotret / syuting / tunas tanaman
shooting = penembakan / pemotretan / syuting film
shop = toko / berbelanja / bengkel
shopping = belanja / perbelanjaan
shore = tepi laut / pantai / pesisir
short = pendek / singkat / kurang
shortly = segera / tidak lama lagi / secara singkat
shot = tembakan / suntikan / foto / percobaan
should = seharusnya / sebaiknya
shoulder = bahu / pundak / memikul tanggung jawab
shout = berteriak / berseru / teriakan
show = menunjukkan / pertunjukan / tampil / terlihat
shower = mandi pancuran / hujan singkat / menghujani
shrug = mengangkat bahu (tanda tidak tahu/tidak peduli)
shut = menutup / tertutup / mengunci
sick = sakit / mual / muak
side = sisi / samping / pihak / berpihak
sigh = menghela napas / desahan
sight = penglihatan / pemandangan / pandangan / membidik
sign = tanda / rambu / menandatangani / isyarat
signal = sinyal / tanda / memberi isyarat
significance = signifikansi / arti penting / makna
significant = signifikan / penting / cukup besar
significantly = secara signifikan / dengan sangat berarti
silence = keheningan / diam / membungkam
silent = diam / hening / bisu
silver = perak / warna perak
similar = mirip / serupa / sejenis
similarly = demikian pula / dengan cara yang sama
simple = sederhana / mudah / biasa
simply = hanya / secara sederhana / benar-benar
sin = dosa / berdosa
since = sejak / karena / semenjak itu
sing = bernyanyi / menyanyikan
singer = penyanyi
single = tunggal / lajang (belum menikah) / satu-satunya
sink = tenggelam / wastafel / bak cuci piring / merosot
sir = tuan / bapak (panggilan hormat)
sister = saudara perempuan
sit = duduk / mendudukkan
site = situs / lokasi / tempat
situation = situasi / keadaan / kondisi
six = enam
size = ukuran / besarnya
ski = bermain ski / papan ski
skill = keterampilan / keahlian / kecakapan
skin = kulit / menguliti
sky = langit / angkasa
slave = budak / bekerja sangat keras
sleep = tidur / istirahat
slice = irisan / mengiris / potongan tipis
slide = meluncur / tergelincir / perosotan / salindia (presentasi)
slight = sedikit / ringan / kecil / meremehkan
slightly = sedikit / agak
slip = terpeleset / tergelincir / menyelinap / secarik kertas
slow = lambat / pelan / memperlambat
slowly = dengan lambat / perlahan-lahan
small = kecil / sedikit
smart = pintar / cerdas / rapi / perih
smell = bau / mencium bau / berbau
smile = senyum / tersenyum
smoke = asap / merokok / mengasapi
smooth = halus / lancar / rata / menghaluskan
snap = mematahkan / menjentikkan jari / membentak / foto cepat
snow = salju / turun salju
so = jadi / begitu / sangat / supaya
so-called = yang disebut-sebut / konon
soccer = sepak bola
social = sosial / kemasyarakatan / ramah
society = masyarakat / perkumpulan / komunitas
soft = lembut / empuk / pelan / ringan
software = perangkat lunak / program komputer
soil = tanah / mengotori
solar = surya / berkaitan dengan matahari
soldier = tentara / prajurit
solid = padat / kokoh / kuat / murni
solution = solusi / pemecahan masalah / larutan
solve = memecahkan / menyelesaikan (masalah)
some = beberapa / sedikit / sekitar
somebody = seseorang
somehow = entah bagaimana / dengan suatu cara
someone = seseorang
something = sesuatu
sometimes = kadang-kadang / terkadang
somewhat = agak / sedikit
somewhere = di suatu tempat / ke suatu tempat
son = anak laki-laki / putra
song = lagu / nyanyian
soon = segera / sebentar lagi
sophisticated = canggih / rumit / berpengalaman
sorry = maaf / menyesal / kasihan
sort = jenis / macam / menyortir / mengelompokkan
soul = jiwa / roh / arwah / musik soul
sound = suara / bunyi / terdengar / sehat/masuk akal
soup = sup / sayur berkuah
source = sumber / asal
south = selatan
southern = bagian selatan
space = ruang / tempat kosong / luar angkasa / jarak
speak = berbicara / berpidato
speaker = pembicara / pengeras suara / ketua parlemen
special = spesial / khusus / istimewa
specialist = spesialis / ahli
species = spesies / jenis makhluk hidup
specific = spesifik / khusus / tertentu
specifically = secara khusus / tepatnya
speech = pidato / ucapan / kemampuan berbicara
speed = kecepatan / mempercepat / ngebut
spend = menghabiskan (uang/waktu) / mengeluarkan
spending = pengeluaran / belanja
spin = berputar / memutar / memintal
spirit = semangat / roh / jiwa / minuman keras
spiritual = spiritual / rohani / batiniah
split = membelah / membagi / berpisah / retakan
spokesman = juru bicara
sport = olahraga
spot = tempat / titik / noda / melihat / mengenali
spread = menyebar / menyebarkan / mengoleskan / bentangan
spring = musim semi / pegas (per) / mata air / melompat
square = persegi / kotak / alun-alun / kuadrat
squeeze = memeras / meremas / menekan / berdesakan
stability = stabilitas / kemantapan / kestabilan
stable = stabil / mantap / kandang kuda
staff = staf / pegawai / tongkat
stage = panggung / tahap / mementaskan
stair = anak tangga / tangga
stake = taruhan / saham / tiang pancang / mempertaruhkan
stand = berdiri / tahan / kedai / pendirian
standard = standar / ukuran baku / patokan
standing = berdiri / kedudukan / reputasi / tetap
star = bintang / pemeran utama / membintangi
stare = menatap tajam / tatapan
start = mulai / memulai / awal / terkejut
state = negara bagian / keadaan / menyatakan
statement = pernyataan / laporan rekening
station = stasiun / pos / menempatkan
statistics = statistik / data angka
status = status / kedudukan / keadaan
stay = tinggal / tetap / menginap
steady = stabil / tetap / mantap / menenangkan
steal = mencuri / merampas / barang murah
steel = baja
step = langkah / melangkah / anak tangga / tahapan
stick = tongkat / ranting / menempel / menusuk / bertahan
still = masih / diam / tenang / namun
stir = mengaduk / bergerak sedikit / membangkitkan emosi
stock = stok / persediaan / saham / kaldu
stomach = perut / lambung / menanggung/menerima
stone = batu / biji buah keras
stop = berhenti / menghentikan / pemberhentian
storage = penyimpanan / gudang
store = toko / menyimpan / menimbun
storm = badai / menyerbu dengan marah
story = cerita / kisah / lantai bangunan (tingkat)
straight = lurus / langsung / jujur / rapi
strange = aneh / asing / tidak biasa
stranger = orang asing / orang tak dikenal
strategic = strategis / penting untuk rencana
strategy = strategi / siasat / rencana
stream = aliran / sungai kecil / mengalir / siaran langsung
street = jalan (di kota)
strength = kekuatan / ketahanan / kelebihan
strengthen = memperkuat / memperkokoh
stress = stres / tekanan / menekankan
stretch = meregangkan / membentang / rentangan
strike = memukul / mogok kerja / menyerang / menyambar
string = tali / senar / rangkaian / merangkai
strip = jalur / potongan panjang / menelanjangi / mengupas
stroke = pukulan / serangan stroke / mengelus / ayunan
strong = kuat / kokoh / tegas / pekat
strongly = dengan kuat / sangat
structure = struktur / bangunan / menyusun
struggle = berjuang / perjuangan / pergulatan
student = siswa / murid / mahasiswa
studio = studio / ruang kerja seniman
study = belajar / mempelajari / penelitian / ruang kerja
stuff = barang / bahan / mengisi penuh
stupid = bodoh / konyol
style = gaya / corak / menata gaya
subject = subjek / mata pelajaran / pokok bahasan / warga negara
submit = menyerahkan / mengajukan / tunduk / patuh
subsequent = berikutnya / selanjutnya / yang menyusul
substance = zat / bahan / inti sari / kekayaan
substantial = substansial / cukup besar / penting / kokoh
succeed = berhasil / sukses / menggantikan (posisi)
success = kesuksesan / keberhasilan
successful = sukses / berhasil
successfully = dengan sukses / dengan berhasil
such = seperti itu / sedemikian / sangat
sudden = tiba-tiba / mendadak
suddenly = dengan tiba-tiba / mendadak
sue = menuntut / menggugat di pengadilan
suffer = menderita / mengalami (hal buruk)
sufficient = cukup / memadai
sugar = gula
suggest = menyarankan / mengusulkan / mengisyaratkan
suggestion = saran / usulan / petunjuk
suicide = bunuh diri
suit = jas / setelan pakaian / cocok / gugatan hukum
summer = musim panas
summit = puncak / konferensi tingkat tinggi (KTT)
sun = matahari / berjemur
super = super / sangat bagus / hebat
supply = pasokan / persediaan / memasok / menyediakan
support = dukungan / mendukung / menopang / memberi nafkah
supporter = pendukung / penggemar
suppose = mengira / menduga / seandainya / seharusnya
supposed = seharusnya / yang diduga / konon
supreme = tertinggi / agung / paling utama
sure = yakin / pasti / tentu saja
surely = pasti / tentu saja / dengan yakin
surface = permukaan / muncul ke permukaan
surgery = operasi / pembedahan / ruang praktik dokter
surprise = kejutan / mengejutkan / keheranan
surprised = terkejut / heran / kaget
surprising = mengejutkan / mengherankan
surprisingly = secara mengejutkan / anehnya
surround = mengelilingi / mengepung
survey = survei / jajak pendapat / meninjau / memeriksa
survival = kelangsungan hidup / bertahan hidup
survive = bertahan hidup / selamat dari / hidup lebih lama dari
survivor = penyintas / orang yang selamat
suspect = mencurigai / menduga / tersangka
sustain = mempertahankan / menopang / mengalami (cedera/kerugian)
swear = bersumpah / berjanji / mengumpat
sweep = menyapu / sapuan / menyebar cepat
sweet = manis / ramah / permen
swim = berenang
swing = berayun / mengayunkan / ayunan / perubahan suasana hati
switch = sakelar / tombol / menukar / beralih
symbol = simbol / lambang / tanda
symptom = gejala / tanda-tanda (penyakit/masalah)
system = sistem / tata cara / jaringan
table = meja / tabel / daftar
tablespoon = sendok makan
tactic = taktik / siasat
tail = ekor / bagian belakang / membuntuti
take = mengambil / membawa / membutuhkan (waktu) / menerima
tale = kisah / cerita / dongeng
talent = bakat / talenta / orang berbakat
talk = berbicara / mengobrol / pembicaraan / ceramah
tall = tinggi (untuk orang/bangunan/pohon)
tank = tangki / kendaraan tempur (tank) / akuarium
tap = mengetuk / keran air / menyadap
tape = pita / kaset / selotip / merekam
target = target / sasaran / menargetkan
task = tugas / pekerjaan
taste = rasa / mencicipi / selera
tax = pajak / memajaki / membebani
taxpayer = wajib pajak / pembayar pajak
tea = teh
teach = mengajar / mengajarkan / mendidik
teacher = guru / pengajar
teaching = pengajaran / ajaran / profesi guru
team = tim / regu / bekerja sama
tear = air mata / merobek / robekan
teaspoon = sendok teh
technical = teknis / berkaitan dengan teknik
technique = teknik / cara / metode
technology = teknologi
teen = remaja (usia 13-19 tahun)
teenager = remaja
telephone = telepon / menelepon
telescope = teleskop / teropong bintang
television = televisi / TV
tell = memberitahu / menceritakan / membedakan / menyuruh
temperature = suhu / temperatur / demam
temporary = sementara / tidak tetap
ten = sepuluh
tend = cenderung / merawat / menjaga
tendency = kecenderungan / tendensi / kecondongan
tennis = tenis
tension = ketegangan / regangan / kekakuan
tent = tenda / kemah
term = istilah / masa / semester / syarat / hubungan
terms = syarat-syarat / ketentuan / hubungan
terrible = mengerikan / sangat buruk / parah
territory = wilayah / teritori / daerah kekuasaan
terror = teror / ketakutan besar
terrorism = terorisme
terrorist = teroris
test = tes / ujian / menguji / memeriksa
testify = bersaksi (di pengadilan) / membuktikan
testimony = kesaksian / bukti
testing = pengujian / pemeriksaan
text = teks / naskah / mengirim pesan singkat
than = daripada / dibandingkan dengan
thank = berterima kasih / syukur
thanks = terima kasih / berkat
that = itu / bahwa / yang
the = itu / ini / sang / si (kata sandang penentu)
theater = teater / gedung bioskop / ruang operasi
their = milik mereka
them = mereka (sebagai objek)
theme = tema / pokok pikiran / lagu tema
themselves = diri mereka sendiri
then = kemudian / lalu / saat itu / kalau begitu
theory = teori / dugaan
therapy = terapi / pengobatan / penyembuhan
there = di sana / ke sana / ada
therefore = oleh karena itu / maka dari itu
these = ini (untuk benda jamak)
they = mereka (sebagai subjek)
thick = tebal / kental / lebat / akrab
thin = tipis / kurus / encer / jarang
thing = benda / hal / barang / sesuatu
think = berpikir / mengira / berpendapat
thinking = pemikiran / cara berpikir
third = ketiga / sepertiga
thirty = tiga puluh
this = ini (untuk benda tunggal)
those = itu (untuk benda jamak)
though = meskipun / walaupun / namun
thought = pikiran / gagasan / berpikir (lampau dari think)
thousand = ribu / seribu
threat = ancaman / bahaya
threaten = mengancam / membahayakan
three = tiga
throat = tenggorokan / kerongkongan
through = melalui / melewati / selesai / karena
throughout = di seluruh / sepanjang (waktu)
throw = melempar / lemparan / membuang
thus = dengan demikian / oleh karena itu / begini
ticket = tiket / karcis / surat tilang
tie = dasi / mengikat / seri (pertandingan) / ikatan
tight = ketat / sempit / kencang / pelit
time = waktu / kali / masa / mengatur waktu
tiny = sangat kecil / mungil
tip = ujung / uang tip / kiat (saran) / memiringkan
tire = ban / melelahkan / menjadi lelah
tired = lelah / capek / bosan
tissue = tisu / jaringan tubuh
title = judul / gelar / hak milik
to = ke / kepada / untuk / sampai
tobacco = tembakau
today = hari ini / masa kini
toe = jari kaki
together = bersama / bersama-sama
tomato = tomat
tomorrow = besok / masa depan
tone = nada / warna / suasana / mengencangkan otot
tongue = lidah / bahasa
tonight = malam ini
too = terlalu / juga
tool = alat / perkakas
tooth = gigi
top = atas / puncak / terbaik / gasing / atasan (baju)
topic = topik / pokok bahasan
toss = melempar ringan / mengundi dengan koin / mengaduk salad
total = total / jumlah keseluruhan / mutlak
totally = sepenuhnya / sama sekali / benar-benar
touch = menyentuh / sentuhan / menghubungi / mengharukan
tough = tangguh / sulit / keras / alot
tour = tur / perjalanan wisata / berkeliling
tourist = turis / wisatawan
tournament = turnamen / kejuaraan
toward = ke arah / menuju / terhadap
towards = ke arah / menuju / terhadap
tower = menara / menjulang tinggi
town = kota kecil / pusat kota
toy = mainan / mempermainkan
trace = jejak / melacak / menjiplak / sedikit sekali
track = jalur / rel / jejak / lagu / melacak
trade = perdagangan / berdagang / menukar / keahlian pekerjaan
tradition = tradisi / adat kebiasaan
traditional = tradisional / menurut adat
traffic = lalu lintas / perdagangan gelap
tragedy = tragedi / peristiwa menyedihkan
trail = jejak / jalur pendakian / tertinggal di belakang / menyeret
train = kereta api / melatih / berlatih
training = pelatihan / latihan
transfer = mentransfer / memindahkan / pindah / kiriman
transform = mengubah bentuk / mentransformasi
transformation = transformasi / perubahan besar
transition = transisi / peralihan / masa pergantian
translate = menerjemahkan / mengartikan
transportation = transportasi / pengangkutan / kendaraan
travel = bepergian / perjalanan / merambat (cahaya/suara)
treat = memperlakukan / mengobati / mentraktir / suguhan istimewa
treatment = perawatan / pengobatan / perlakuan
treaty = perjanjian internasional / pakta
tree = pohon
tremendous = luar biasa / sangat besar / hebat
trend = tren / kecenderungan / arah perkembangan
trial = persidangan / uji coba / cobaan hidup
tribe = suku / marga
trick = trik / tipuan / menipu / keahlian khusus
trip = perjalanan / tersandung / menjegal
troop = pasukan / kawanan / berbondong-bondong
trouble = masalah / kesulitan / mengganggu / repot
truck = truk / mengangkut dengan truk
true = benar / sejati / asli / setia
truly = benar-benar / sungguh / dengan tulus
trust = percaya / kepercayaan / mempercayakan
truth = kebenaran / kenyataan
try = mencoba / berusaha / mengadili / cobaan
tube = tabung / pipa / kereta bawah tanah / layar TV
tunnel = terowongan / menggali terowongan
turn = berbelok / memutar / giliran / berubah menjadi
TV = televisi / TV
twelve = dua belas
twenty = dua puluh
twice = dua kali / dua kali lipat
twin = kembar / pasangan identik
two = dua
type = tipe / jenis / mengetik
typical = tipikal / khas / biasa
typically = biasanya / pada umumnya / secara khas
ugly = jelek / buruk rupa / tidak menyenangkan
ultimate = terakhir / paling utama / terbaik / puncak
ultimately = pada akhirnya / akhirnya
unable = tidak mampu / tidak bisa
uncle = paman
under = di bawah / kurang dari / dalam proses
undergo = menjalani / mengalami
understand = mengerti / memahami
understanding = pemahaman / pengertian / kesepakatan
unfortunately = sayangnya / celakanya
uniform = seragam / sama rata
union = serikat pekerja / persatuan / pernikahan
unique = unik / khas / satu-satunya
unit = unit / satuan / kelompok
united = bersatu / gabungan
universal = universal / umum / berlaku untuk semua
universe = alam semesta / jagat raya
university = universitas / perguruan tinggi
unknown = tidak dikenal / tidak diketahui
unless = kecuali jika / kalau tidak
unlike = tidak seperti / berbeda dengan
unlikely = tidak mungkin / kecil kemungkinannya
until = sampai / hingga
unusual = tidak biasa / aneh / luar biasa
up = naik / ke atas / bangun / habis (waktu)
upon = di atas / segera setelah / pada
upper = bagian atas / lebih tinggi
urban = perkotaan / berkaitan dengan kota
urge = mendesak / mendorong / dorongan kuat
us = kita / kami (sebagai objek)
use = menggunakan / memakai / kegunaan / manfaat
used = bekas / terbiasa / digunakan
useful = berguna / bermanfaat
user = pengguna / pemakai
usual = biasa / lazim
usually = biasanya / umumnya
utility = kegunaan / layanan umum (listrik/air)
vacation = liburan / masa libur
valley = lembah
valuable = berharga / bernilai tinggi
value = nilai / harga / menghargai / prinsip hidup
variable = variabel / berubah-ubah / tidak tetap
variation = variasi / perubahan / perbedaan
variety = variasi / keragaman / jenis
various = berbagai / bermacam-macam
vary = bervariasi / berbeda-beda / mengubah
vast = sangat luas / sangat besar
vegetable = sayuran / nabati
vehicle = kendaraan / sarana penyampai
venture = usaha bisnis berisiko / memberanikan diri
version = versi / terjemahan / pandangan
versus = lawan / melawan / dibandingkan dengan
very = sangat / amat / tepat (itu juga)
vessel = kapal besar / wadah / pembuluh darah
veteran = veteran / orang berpengalaman
via = melalui / lewat / dengan perantaraan
victim = korban
victory = kemenangan / kejayaan
video = video / rekaman gambar
view = pemandangan / pandangan / melihat / menganggap
viewer = penonton / pemirsa / alat peninjau
village = desa / kampung
violate = melanggar / merusak / memperkosa
violation = pelanggaran / penodaan
violence = kekerasan / kekejaman
violent = kasar / penuh kekerasan / dahsyat
virtually = hampir / secara virtual (maya) / pada dasarnya
virtue = kebajikan / kebaikan / keunggulan
virus = virus
visible = terlihat / tampak / jelas
vision = penglihatan / visi / pandangan masa depan / khayalan
visit = mengunjungi / kunjungan / bertamu
visitor = pengunjung / tamu
visual = visual / berkaitan dengan penglihatan
vital = vital / sangat penting / penuh semangat hidup
voice = suara (manusia) / menyuarakan / pendapat
volume = volume / isi / tingkat suara / jilid buku
volunteer = sukarelawan / relawan / mengajukan diri secara sukarela
vote = memilih / suara (pemilu) / pemungutan suara
voter = pemilih / pemberi suara
vs = lawan / melawan (singkatan dari versus)
vulnerable = rentan / mudah diserang / rawan
wage = upah / gaji / melancarkan (perang/kampanye)
wait = menunggu / menanti / waktu tunggu
wake = bangun / membangunkan / jejak gelombang kapal
walk = berjalan / jalan-jalan / memapah
wall = dinding / tembok / membatasi
wander = mengembara / berkelana / melantur (pikiran)
want = ingin / menginginkan / kekurangan
war = perang / berperang
warm = hangat / menghangatkan / ramah
warn = memperingatkan / memberi tahu bahaya
warning = peringatan / tanda bahaya
wash = mencuci / membersihkan / cucian
waste = limbah / sampah / membuang-buang / sia-sia
watch = menonton / memperhatikan / jam tangan / berjaga
water = air / menyiram / berair
wave = gelombang / ombak / melambaikan tangan
way = jalan / cara / arah / sangat jauh
we = kita / kami (sebagai subjek)
weak = lemah / tidak kuat / encer
wealth = kekayaan / harta benda / kelimpahan
wealthy = kaya / makmur
weapon = senjata
wear = memakai / mengenakan / aus (rusak karena dipakai)
weather = cuaca / melewati masa sulit
wedding = pernikahan / pesta perkawinan
week = minggu / pekan
weekend = akhir pekan
weekly = mingguan / setiap minggu
weigh = menimbang / memiliki berat / mempertimbangkan
weight = berat / bobot / beban / pemberat
welcome = selamat datang / menyambut / diterima dengan senang hati
welfare = kesejahteraan / bantuan sosial pemerintah
well = baik / sehat / sumur / yah (kata seru)
west = barat
western = bagian barat / budaya barat
wet = basah / membasahi / hujan
what = apa / yang mana / betapa
whatever = apa pun / terserah
wheel = roda / kemudi / memutar
when = kapan / ketika / saat
whenever = kapan pun / setiap kali
where = di mana / ke mana / tempat
whereas = sedangkan / padahal / mengingat
wherever = di mana pun / ke mana pun
whether = apakah / baik... maupun...
which = yang mana / yang
while = sementara / sedangkan / saat / sebentar
whisper = berbisik / bisikan / desas-desus
white = putih / pucat
who = siapa / yang (untuk orang)
whole = seluruh / utuh / keseluruhan
whom = siapa / yang (untuk objek orang)
whose = milik siapa / yang miliknya
why = mengapa / kenapa / alasan
wide = lebar / luas / terbuka penuh
widely = secara luas / oleh banyak orang
widespread = tersebar luas / merata
wife = istri
wild = liar / buas / sangat antusias / alam liar
will = akan / kemauan / tekad / surat wasiat
willing = bersedia / mau / rela
win = menang / memenangkan / kemenangan
wind = angin / memutar / berliku-liku
window = jendela / etalase / peluang waktu
wine = anggur (minuman) / menjamu
wing = sayap / bagian samping gedung / terbang
winner = pemenang / juara
winter = musim dingin
wipe = mengelap / menyeka / menghapus
wire = kawat / kabel / mengirim telegram/uang
wisdom = kebijaksanaan / kearifan
wise = bijaksana / arif / pintar
wish = berharap / keinginan / mendoakan
with = dengan / bersama / memiliki
withdraw = menarik (uang/pasukan) / mengundurkan diri
within = di dalam / dalam kurun waktu / tidak melebihi
without = tanpa / di luar
witness = saksi / menyaksikan / menjadi bukti
woman = wanita / perempuan dewasa
wonder = bertanya-tanya / heran / keajaiban
wonderful = luar biasa / menakjubkan / sangat bagus
wood = kayu / hutan kecil
wooden = terbuat dari kayu / kaku
word = kata / ucapan / janji / kabar
work = bekerja / pekerjaan / karya / berfungsi
worker = pekerja / buruh / karyawan
working = bekerja / berfungsi / kelas pekerja
works = karya seni/sastra / pabrik / mesin
workshop = bengkel / lokakarya (pelatihan)
world = dunia / bumi / alam
worried = khawatir / cemas
worry = khawatir / mencemaskan / kekhawatiran
worth = bernilai / sepadan / nilai / kekayaan
would = akan / dulu sering (bentuk lampau dari will)
wound = luka / melukai / memutar (lampau dari wind)
wrap = membungkus / melilitkan / selendang / selesai (syuting)
write = menulis / mengarang / berkirim surat
writer = penulis / pengarang
writing = tulisan / penulisan / karya tulis
wrong = salah / keliru / tidak adil / kesalahan
yard = halaman / pekarangan / yard (ukuran panjang 0,9 meter)
yeah = ya (santai)
year = tahun
yell = berteriak / membentak / teriakan
yellow = kuning / pengecut
yes = ya / setuju
yesterday = kemarin / masa lalu yang baru lewat
yet = belum / namun / masih / lagi
yield = menghasilkan / menyerah / memberi jalan / hasil panen
you = kamu / Anda / kalian
young = muda / anak hewan
your = milikmu / milik Anda / milik kalian
yours = milikmu / milik Anda / milik kalian (tanpa diikuti benda)
yourself = dirimu sendiri / diri Anda sendiri
youth = masa muda / pemuda / kaum muda
zone = zona / wilayah / daerah / membagi wilayah
`.trim();